FROM node:20-alpine AS builder

WORKDIR /app

# Build args - Railway passes env vars as build args automatically
ARG SUPABASE_URL
ARG SUPABASE_KEY
ARG NUXT_SUPABASE_SERVICE_ROLE_KEY
ARG NUXT_OPENROUTER_API_KEY
ARG NUXT_PUBLIC_APP_URL
ARG NUXT_APP_URL
ARG NUXT_PUBLIC_FIREBASE_API_KEY
ARG NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NUXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NUXT_PUBLIC_FIREBASE_APP_ID
ARG NUXT_PUBLIC_FIREBASE_VAPID_KEY

# Make build args available as env vars during build
ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_KEY=$SUPABASE_KEY
ENV NUXT_SUPABASE_SERVICE_ROLE_KEY=$NUXT_SUPABASE_SERVICE_ROLE_KEY
ENV NUXT_OPENROUTER_API_KEY=$NUXT_OPENROUTER_API_KEY
ENV NUXT_PUBLIC_APP_URL=$NUXT_PUBLIC_APP_URL
ENV NUXT_APP_URL=$NUXT_APP_URL
ENV NUXT_PUBLIC_FIREBASE_API_KEY=$NUXT_PUBLIC_FIREBASE_API_KEY
ENV NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NUXT_PUBLIC_FIREBASE_PROJECT_ID=$NUXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NUXT_PUBLIC_FIREBASE_APP_ID=$NUXT_PUBLIC_FIREBASE_APP_ID
ENV NUXT_PUBLIC_FIREBASE_VAPID_KEY=$NUXT_PUBLIC_FIREBASE_VAPID_KEY

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

COPY --from=builder /app/.output .output

ENV HOST=0.0.0.0
ENV PORT=8080
ENV NODE_ENV=production

EXPOSE 8080

CMD ["node", ".output/server/index.mjs"]
