[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["NODE_ENV=production npm run build"]

[start]
cmd = "NODE_ENV=production HOST=0.0.0.0 PORT=8080 node .output/server/index.mjs"
