export type AppLanguage = 'es' | 'en'

/** Persisted language preference — shared across all components via module-level ref */
const currentLanguage = ref<AppLanguage>(
  (typeof localStorage !== 'undefined' ? localStorage.getItem('focusflow_lang') as AppLanguage : null) || 'es'
)

export function useLanguage() {
  function setLanguage(lang: AppLanguage) {
    currentLanguage.value = lang
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem('focusflow_lang', lang)
    }
  }

  function toggleLanguage() {
    setLanguage(currentLanguage.value === 'es' ? 'en' : 'es')
  }

  /** Get the localized title for a task based on current language */
  function localizedTitle(task: { title: string; title_en?: string }): string {
    if (currentLanguage.value === 'en' && task.title_en) return task.title_en
    return task.title
  }

  /** Get the localized description for a task based on current language */
  function localizedDescription(task: { description?: string; description_en?: string }): string {
    if (currentLanguage.value === 'en' && task.description_en) return task.description_en
    return task.description || ''
  }

  /** UI labels for common elements */
  const labels = computed(() => {
    const en = currentLanguage.value === 'en'
    return {
      // ── Common ──
      newTask: en ? 'New task' : 'Nueva tarea',
      description: en ? 'Description' : 'Descripción',
      priority: en ? 'Priority' : 'Prioridad',
      dueDate: en ? 'Due date' : 'Fecha límite',
      column: en ? 'Column' : 'Columna',
      estimation: en ? 'Estimation (hours)' : 'Estimación (horas)',
      assigned: en ? 'Assigned' : 'Asignados',
      tags: en ? 'Tags' : 'Etiquetas',
      save: en ? 'Save' : 'Guardar',
      close: en ? 'Close' : 'Cerrar',
      cancel: en ? 'Cancel' : 'Cancelar',
      create: en ? 'Create task' : 'Crear tarea',
      delete: en ? 'Delete' : 'Eliminar',
      deleteConfirm: en ? 'Delete this task?' : '¿Eliminar esta tarea?',
      addDescription: en ? 'Add a detailed description...' : 'Agrega una descripción detallada...',
      priorityLow: en ? 'Low' : 'Baja',
      priorityMedium: en ? 'Medium' : 'Media',
      priorityHigh: en ? 'High' : 'Alta',
      priorityCritical: en ? 'Critical' : 'Crítica',
      import: en ? 'Import' : 'Importar',
      noTranslation: en ? '(No translation available)' : '(Sin traducción disponible)',
      loading: en ? 'Loading...' : 'Cargando...',
      error: en ? 'Error' : 'Error',
      confirm: en ? 'Confirm' : 'Confirmar',
      optional: en ? 'Optional' : 'Opcional',
      noResults: en ? 'No results' : 'Sin resultados',
      search: en ? 'Search' : 'Buscar',
      clear: en ? 'Clear' : 'Limpiar',
      selectAll: en ? 'Select all' : 'Seleccionar todos',
      you: en ? 'You' : 'Tú',
      role: en ? 'Role' : 'Rol',
      email: en ? 'Email' : 'Email',

      // ── Dashboard ──
      goodMorning: en ? 'Good morning' : 'Buenos días',
      goodAfternoon: en ? 'Good afternoon' : 'Buenas tardes',
      goodEvening: en ? 'Good evening' : 'Buenas noches',
      totalTasks: en ? 'Total Tasks' : 'Tareas Totales',
      inProgress: en ? 'In Progress' : 'En Progreso',
      completed: en ? 'Completed' : 'Completadas',
      projectSummary: en ? 'Project Summary' : 'Resumen de Proyectos',
      thisMonth: en ? 'This Month' : 'Este Mes',
      tokenUsage: en ? 'AI Token Usage' : 'Uso de Tokens AI',
      update: en ? 'Update' : 'Actualizar',
      pomodoroTimer: en ? 'Pomodoro Timer' : 'Pomodoro Timer',
      focusSession: en ? 'Focus session' : 'Sesión de enfoque',
      breakTime: en ? 'Break time' : 'Descanso',
      start: en ? 'Start' : 'Iniciar',
      pause: en ? 'Pause' : 'Pausar',
      reset: en ? 'Reset' : 'Reiniciar',
      sessions: en ? 'sessions' : 'sesiones',
      dayStreak: en ? 'day streak' : 'días seguidos',
      board: en ? 'Board' : 'Tablero',
      viewAll: en ? 'View all' : 'Ver todo',
      name: en ? 'Name' : 'Nombre',
      project: en ? 'Project' : 'Proyecto',
      date: en ? 'Date' : 'Fecha',
      status: en ? 'Status' : 'Estado',
      deadline: en ? 'Deadline' : 'Deadline',
      done: en ? 'Done' : 'Hecho',
      pending: en ? 'Pending' : 'Pendiente',
      all: en ? 'All' : 'Todos',
      filters: en ? 'Filters' : 'Filtros',
      projectRanking: en ? 'Project Ranking' : 'Ranking de Proyectos',
      tasks: en ? 'tasks' : 'tareas',
      createProject: en ? 'Create project' : 'Crear proyecto',
      noProjects: en ? 'No projects yet' : 'Sin proyectos aún',
      antiProcrastination: en ? 'Anti-Procrastination Coach' : 'Coach Anti-Procrastinación',
      analyzeNow: en ? 'Analyze now' : 'Analizar ahora',
      quickWins: en ? 'Quick Wins' : 'Victorias rápidas',
      dailyPlan: en ? 'Daily Plan' : 'Plan del día',
      generatePlan: en ? 'Generate plan with AI' : 'Generar plan con IA',
      focusTasks: en ? 'Focus Tasks' : 'Tareas de enfoque',
      viewProjects: en ? 'View projects' : 'Ver proyectos',
      newProject: en ? 'New project' : 'Nuevo proyecto',
      general: en ? 'General' : 'General',
      daily: en ? 'Daily' : 'Diario',
      today: en ? 'Today' : 'Hoy',
      vsYesterday: en ? 'vs yesterday' : 'vs ayer',
      last7days: en ? 'Last 7 days' : 'Últimos 7 días',
      avgPerCall: en ? 'Avg per call' : 'Promedio por llamada',
      enableNotifications: en ? 'Enable notifications' : 'Activar notificaciones',
      tokensUsed: en ? 'Tokens Used' : 'Tokens Usados',
      sessionsToday: en ? 'Sessions today' : 'Sesiones hoy',
      streak: en ? 'Streak' : 'Racha',
      days: en ? 'days' : 'dias',
      focusedOn: en ? 'Focused on' : 'Enfocado en',
      freeSession: en ? 'Free session' : 'Sesión libre',
      allTasks: en ? 'All tasks' : 'Todas las tareas',
      noRecentTasks: en ? 'No recent tasks' : 'No hay tareas recientes',
      noFilterResults: en ? 'No results with these filters' : 'Sin resultados con estos filtros',
      procrastinationRisk: en ? 'Procrastination risk' : 'Riesgo de procrastinación',
      todaysSessions: en ? "Today's Sessions" : 'Sesiones de hoy',
      used: en ? 'used' : 'usado',
      analyzing: en ? 'Analyzing...' : 'Analizando...',
      whatsBlocking: en ? "What's blocking you today?" : '¿Qué te está bloqueando hoy?',
      projectName: en ? 'Project name' : 'Nombre del proyecto',
      kanbanTemplate: en ? 'Kanban Template' : 'Plantilla Kanban',

      // ── Navigation / Layout ──
      dashboard: en ? 'Dashboard' : 'Dashboard',
      projects: en ? 'Projects' : 'Proyectos',
      aiAgents: en ? 'AI Agents' : 'AI Agents',
      files: en ? 'Files' : 'Archivos',
      team: en ? 'Team' : 'Equipo',
      settings: en ? 'Settings' : 'Ajustes',
      home: en ? 'Home' : 'Home',

      // ── Team page ──
      teamTitle: en ? 'Team' : 'Equipo',
      membersCount: en ? 'members in workspace' : 'miembros en el workspace',
      memberSingular: en ? 'member' : 'miembro',
      scheduleMeeting: en ? 'Schedule meeting' : 'Programar reunión',
      invite: en ? 'Invite' : 'Invitar',
      upcomingMeetings: en ? 'Upcoming meetings' : 'Próximas reuniones',
      join: en ? 'Join' : 'Unirse',
      participants: en ? 'participants' : 'participantes',
      loadingTeam: en ? 'Loading team...' : 'Cargando equipo...',
      noEmail: en ? 'No email' : 'Sin email',
      joined: en ? 'Joined' : 'Se unió',
      allProjects: en ? 'All projects' : 'Todos los proyectos',
      noProjectAccess: en ? 'No project access' : 'Sin acceso a proyectos',
      addToProject: en ? 'Add to project' : 'Añadir a proyecto',
      manageAccess: en ? 'Manage all access' : 'Gestionar todos los accesos',
      alreadyHasAll: en ? 'Already has access to all' : 'Ya tiene acceso a todos',
      removeFromTeam: en ? 'Remove from team' : 'Remover del equipo',
      removeFromProject: en ? 'Remove from project' : 'Quitar de este proyecto',
      noMembers: en ? 'No members' : 'Sin miembros',
      inviteTeam: en ? 'Invite your team to collaborate' : 'Invita a tu equipo para colaborar',
      inviteMember: en ? 'Invite member' : 'Invitar miembro',
      inviteDesc: en ? 'The user must have a FocusFlow account' : 'El usuario debe tener una cuenta en FocusFlow',
      userEmail: en ? 'User email' : 'Email del usuario',
      projectAccess: en ? 'Project access' : 'Acceso a proyectos',
      adminAutoAccess: en ? 'Admin+ roles have automatic access to all projects' : 'Los roles admin+ tienen acceso automático a todos los proyectos',
      addedToTeam: en ? 'added to team' : 'agregado al equipo',
      errorInviting: en ? 'Error inviting' : 'Error al invitar',
      errorChangingRole: en ? 'Error changing role' : 'Error al cambiar rol',
      confirmRemoveMember: en ? 'Remove "{name}" from team?' : '¿Remover a "{name}" del equipo?',
      errorRemovingMember: en ? 'Error removing member' : 'Error al remover miembro',
      errorAddingProject: en ? 'Error adding project' : 'Error al añadir proyecto',
      errorRemovingProject: en ? 'Error removing project' : 'Error al quitar proyecto',
      errorUpdatingAccess: en ? 'Error updating access' : 'Error al actualizar acceso',
      member: en ? 'Member' : 'Miembro',
      viewer: en ? 'Viewer' : 'Viewer',
      admin: en ? 'Admin' : 'Admin',
      owner: en ? 'Owner' : 'Owner',
      superadmin: en ? 'Superadmin' : 'Superadmin',

      // ── Procrastination metrics ──
      procrastinationMetrics: en ? 'Productivity metrics' : 'Métricas de productividad',
      showMetrics: en ? 'Show metrics' : 'Mostrar métricas',
      hideMetrics: en ? 'Hide metrics' : 'Ocultar métricas',
      procrastinationIndex: en ? 'Procrastination Index' : 'Índice de procrastinación',
      procrastinationIndexDesc: en ? 'Weighted score from task behavior (0 = ideal, 100 = high procrastination)' : 'Puntaje ponderado del comportamiento con tareas (0 = ideal, 100 = alta procrastinación)',
      overdueRate: en ? 'Overdue Rate' : 'Tasa de atraso',
      overdueRateDesc: en ? 'Percentage of tasks past due date still not completed' : 'Porcentaje de tareas pasadas de fecha que aún no se completan',
      lateCompletionRate: en ? 'Late Completion' : 'Completado tardío',
      lateCompletionRateDesc: en ? 'Percentage of tasks completed after the due date' : 'Porcentaje de tareas completadas después de la fecha límite',
      stagnationScore: en ? 'Stagnation' : 'Estancamiento',
      stagnationScoreDesc: en ? 'Average inactivity on open tasks (30+ days = max score)' : 'Promedio de inactividad en tareas abiertas (30+ días = puntaje máximo)',
      effortGap: en ? 'Effort Gap' : 'Brecha de esfuerzo',
      effortGapDesc: en ? 'Difference between estimated and tracked hours' : 'Diferencia entre horas estimadas y registradas',
      quizScore: en ? 'Quiz Score' : 'Puntaje del quiz',
      quizScoreDesc: en ? 'Self-assessment procrastination quiz result' : 'Resultado del quiz de autoevaluación de procrastinación',
      noTaskData: en ? 'No task data' : 'Sin datos de tareas',
      lowRisk: en ? 'Low' : 'Bajo',
      moderateRisk: en ? 'Moderate' : 'Moderado',
      highRisk: en ? 'High' : 'Alto',
      tasksTracked: en ? 'tasks tracked' : 'tareas rastreadas',
      loadingMetrics: en ? 'Loading metrics...' : 'Cargando métricas...',

      // ── Kanban ──
      aiSuggestions: en ? 'AI Suggestions' : 'AI Sugerencias',
      createTask: en ? 'Create task' : 'Crear tarea',
      loadingBoard: en ? 'Loading board...' : 'Cargando tablero...',
      editColumn: en ? 'Edit column' : 'Editar columna',
      deleteColumn: en ? 'Delete column' : 'Eliminar columna',
      columnName: en ? 'Column name' : 'Nombre de la columna',
      assignedTo: en ? 'Assigned to' : 'Asignado a',
      noTasksMobile: en ? 'No tasks' : 'Sin tareas',
      noTasksDrag: en ? 'Drag tasks here' : 'Arrastra tareas aquí',
      createAllOnBoard: en ? 'Create all on board' : 'Crear todas en el tablero',
      dueToday: en ? 'Due Today' : 'Vencen Hoy',
      startPomodoro: en ? 'Start Pomodoro' : 'Iniciar Pomodoro',
      improveWithAI: en ? 'Improve with AI' : 'Mejorar con AI',
      deleteTask: en ? 'Delete task' : 'Eliminar tarea',
      noEstimate: en ? 'No estimate' : 'Sin estimación',
      whatToDo: en ? 'What needs to be done?' : '¿Qué hay que hacer?',
      describeTask: en ? 'Describe the task...' : 'Describe la tarea...',
      addToBoard: en ? 'Add task to board' : 'Agrega una tarea al tablero',
      tagsSeparated: en ? 'Tags (comma separated)' : 'Etiquetas (separadas por coma)',
      tagPlaceholder: en ? 'bug, frontend, urgent...' : 'bug, frontend, urgente...',
      errorCreating: en ? 'Error creating task' : 'Error al crear tarea',
      title: en ? 'Title' : 'Título',

      // ── Agents ──
      agentsDesc: en ? 'Task management and documentation agents with session memory' : 'Agentes de gestión de tareas y documentación con memoria por sesión',
      selectProject: en ? 'Select a project...' : 'Selecciona un proyecto...',
      noAIPermission: en ? 'You don\'t have permission to use AI agents' : 'No tienes permisos para usar los agentes AI',
      selectProjectFirst: en ? 'Select a project to run agents' : 'Selecciona un proyecto para ejecutar los agentes',
      taskManagement: en ? 'Task Management' : 'Gestión de Tareas',
      documentation: en ? 'Documentation' : 'Documentación',
      running: en ? 'Running...' : 'Ejecutando...',
      generating: en ? 'Generating...' : 'Generando...',
      generateDocs: en ? 'Generate documentation' : 'Generar documentación',
      improveTasks: en ? 'Improve tasks' : 'Mejorar tareas',
      analyzeLoad: en ? 'Analyze load' : 'Analizar carga',
      execute: en ? 'Execute' : 'Ejecutar',
      tasksCreated: en ? 'tasks created' : 'tareas creadas',
      tasksImproved: en ? 'tasks improved' : 'tareas mejoradas',
      health: en ? 'Health:' : 'Salud:',
      estimatedHours: en ? 'h estimated' : 'h estimadas',
      bottlenecks: en ? 'Bottlenecks' : 'Cuellos de botella',
      recommendations: en ? 'Recommendations' : 'Recomendaciones',
      sections: en ? 'Sections' : 'Secciones',
      more: en ? 'more...' : 'más...',
      savedMd: en ? '.md saved' : '.md guardado',

      // ── Projects page ──
      totalProjects: en ? 'Total Projects' : 'Proyectos Totales',
      sprintBoard: en ? 'Board — Sprint Tasks' : 'Tablero — Tareas del Sprint',
      workspaceNotFound: en ? 'Workspace not found' : 'Workspace no encontrado',
      createWorkspaceFirst: en ? 'You need to create a workspace first' : 'Necesitas crear un workspace primero',
      createWorkspace: en ? 'Create workspace' : 'Crear workspace',
      noProjectsDesc: en ? 'Create your first project to organize tasks in a Kanban board' : 'Crea tu primer proyecto para organizar tareas en un tablero Kanban',
      createFirstProject: en ? 'Create first project' : 'Crear primer proyecto',
      configureProject: en ? 'Configure your project details' : 'Configura los detalles de tu proyecto',
      projectNamePlaceholder: en ? 'e.g. Mobile App, API v2...' : 'Ej: App Mobile, API v2...',
      descriptionOptional: en ? 'Description (optional)' : 'Descripción (opcional)',
      whatIsProject: en ? 'What is this project about?' : '¿De qué trata este proyecto?',
      columns: en ? 'columns' : 'columnas',
      active: en ? 'Active' : 'Activo',
      planning: en ? 'Planning' : 'Planificación',
      review: en ? 'Review' : 'Revisión',
      paused: en ? 'Paused' : 'Pausado',

      // ── Files page ──
      filesTitle: en ? 'Files' : 'Archivos',
      filesDesc: en ? 'Manage your workspace documents' : 'Gestiona los documentos de tu workspace',
      uploadFile: en ? 'Upload file' : 'Subir archivo',
      loadingFiles: en ? 'Loading files...' : 'Cargando archivos...',
      noFiles: en ? 'No files' : 'Sin archivos',
      noFilesDesc: en ? 'Upload files or generate documents with AI to see them here' : 'Sube archivos o genera documentos con AI para verlos aquí',
      folders: en ? 'Folders' : 'Carpetas',
      download: en ? 'Download' : 'Descargar',
      confirmDeleteFile: en ? 'Delete "{name}"?' : '¿Eliminar "{name}"?',
      errorUploading: en ? 'Error uploading file' : 'Error al subir archivo',
      errorDownloading: en ? 'Error downloading' : 'Error al descargar',
      errorDeletingFile: en ? 'Error deleting file. Try again.' : 'Error al eliminar archivo. Intenta de nuevo.',

      // ── Settings page ──
      settingsTitle: en ? 'Settings' : 'Ajustes',
      workspaceConfig: en ? 'General workspace configuration' : 'Configuración general del espacio de trabajo',
      slugUrl: en ? 'Slug (URL)' : 'Slug (URL)',
      saveChanges: en ? 'Save changes' : 'Guardar cambios',
      savedSuccess: en ? 'Saved successfully' : 'Guardado correctamente',
      yourProfile: en ? 'Your profile' : 'Tu perfil',
      accountInfo: en ? 'Your account information' : 'Información de tu cuenta',
      dangerZone: en ? 'Danger zone' : 'Zona de peligro',
      irreversibleActions: en ? 'Irreversible actions' : 'Acciones irreversibles',
      logout: en ? 'Log out' : 'Cerrar sesión',
      logoutDesc: en ? 'Sign out from your account on this device' : 'Salir de tu cuenta en este dispositivo',

      // ── Meeting modal ──
      scheduleMeetingTitle: en ? 'Schedule meeting' : 'Programar reunión',
      meetingTitle: en ? 'Meeting title' : 'Título de la reunión',
      meetingTitlePlaceholder: en ? 'e.g. Sprint Review, Daily Standup...' : 'Ej: Sprint Review, Daily Standup...',
      meetingAgenda: en ? 'Meeting agenda...' : 'Agenda de la reunión...',
      dateTime: en ? 'Date and time' : 'Fecha y hora',
      duration: en ? 'Duration' : 'Duración',
      projectOptional: en ? 'Project (optional)' : 'Proyecto (opcional)',
      noProjectOption: en ? 'No project' : 'Sin proyecto',
      attendees: en ? 'Attendees' : 'Participantes',
      attendeesSelected: en ? 'attendee(s) selected — they will receive an email with Google Meet link' : 'participante(s) seleccionado(s) — recibirán email con enlace de Google Meet',
      meetAutoGenerate: en ? 'A Meet link will be generated automatically' : 'Se generará automáticamente un enlace de Meet',
      meetingScheduled: en ? 'Meeting scheduled' : 'Reunión programada',
      invitationsSent: en ? 'Email invitations sent to' : 'Se enviaron invitaciones por email a',
      schedule: en ? 'Schedule' : 'Programar',
      errorScheduling: en ? 'Error scheduling meeting' : 'Error al programar reunión',
      hour1: en ? '1 hour' : '1 hora',
      hours1_5: en ? '1.5 hours' : '1.5 horas',
      hours2: en ? '2 hours' : '2 horas',

      // ── Import modal ──
      importTasks: en ? 'Import tasks' : 'Importar tareas',
      compatiblePlatforms: en ? 'Compatible platforms' : 'Plataformas compatibles',
      genericCsv: en ? 'Generic CSV' : 'CSV genérico',
      targetColumn: en ? 'Target column (default)' : 'Columna destino (por defecto)',
      firstColumn: en ? 'First column' : 'Primera columna',
      mapColumnsLabel: en ? 'Map CSV status/columns to project columns' : 'Mapear status/columnas del CSV a las columnas del proyecto',
      pasteOrUpload: en ? 'Paste CSV or upload file' : 'Pegar CSV o subir archivo',
      uploadCsv: en ? 'Upload .csv file' : 'Subir archivo .csv',
      rowsDetected: en ? 'rows detected' : 'filas detectadas',
      dropFileHere: en ? 'Drop the file here' : 'Suelta el archivo aquí',
      dragDropCsv: en ? 'Drag a CSV file here' : 'Arrastra un archivo CSV aquí',
      orClickBrowse: en ? 'or click to browse' : 'o haz clic para buscar',
      orPasteBelow: en ? 'or paste below' : 'o pega abajo',
      replaceFile: en ? 'Replace file' : 'Reemplazar archivo',
      preview: en ? 'Preview:' : 'Vista previa:',
      moreTasks: en ? 'more tasks...' : 'tareas más...',
      tasksImported: en ? 'tasks imported successfully' : 'tareas importadas correctamente',
      formatDetected: en ? 'Format detected:' : 'Formato detectado:',
      errorImporting: en ? 'Error importing' : 'Error al importar',

      // ── Attachments ──
      attachments: en ? 'Attachments' : 'Adjuntos',
      addAttachment: en ? '+ Add' : '+ Agregar',
      dragFilesHere: en ? 'Drag files here or' : 'Arrastra archivos aquí o',
      selectFiles: en ? 'select' : 'selecciona',
      uploading: en ? 'Uploading...' : 'Subiendo...',

      // ── Labels ──
      labels: en ? 'Labels' : 'Labels',
      labelName: en ? 'Label name' : 'Nombre del label',
      createLabel: en ? '+ Create label' : '+ Crear label',
      suggestionsLabel: en ? 'Suggestions:' : 'Sugerencias:',
      urgent: en ? 'Urgent' : 'Urgente',

      // ── Notifications ──
      notifications: en ? 'Notifications' : 'Notificaciones',
      markAllRead: en ? 'Mark all read' : 'Marcar todo leído',
      noNotifications: en ? 'No notifications' : 'Sin notificaciones',
      now: en ? 'now' : 'ahora',
      minutesAgo: en ? 'm ago' : 'm',
      hoursAgo: en ? 'h ago' : 'h',
      daysAgo: en ? 'd ago' : 'd',

      // ── Auth pages ──
      createYourAccount: en ? 'Create your account' : 'Crea tu cuenta',
      startManaging: en ? 'Start managing your projects today' : 'Empieza a gestionar tus proyectos hoy',
      password: en ? 'Password' : 'Contraseña',
      confirmPassword: en ? 'Confirm password' : 'Confirmar contraseña',
      minChars: en ? 'At least 6 characters' : 'Mínimo 6 caracteres',
      repeatPassword: en ? 'Repeat password' : 'Repetir contraseña',
      createAccountBtn: en ? 'Create account' : 'Crear cuenta',
      orContinueWith: en ? 'or continue with' : 'o continua con',
      alreadyHaveAccount: en ? 'Already have an account?' : '¿Ya tienes cuenta?',
      signIn: en ? 'Sign in' : 'Inicia sesión',
      welcomeBack: en ? 'Welcome back' : 'Bienvenido de nuevo',
      loginSubtitle: en ? 'Sign in to continue with your projects' : 'Inicia sesión para continuar con tus proyectos',
      enterPassword: en ? 'Enter your password' : 'Ingresa tu contraseña',
      signInBtn: en ? 'Sign in' : 'Iniciar sesión',
      noAccount: en ? "Don't have an account?" : '¿No tienes cuenta?',
      passwordsMismatch: en ? 'Passwords do not match' : 'Las contraseñas no coinciden',
      passwordTooShort: en ? 'Password must be at least 6 characters' : 'La contraseña debe tener al menos 6 caracteres',
      registerError: en ? 'Error signing up' : 'Error al registrarse',
      loginError: en ? 'Wrong email or password' : 'Email o contraseña incorrectos',
      googleError: en ? 'Error with Google' : 'Error con Google',

      // ── Onboarding ──
      setupWorkspace: en ? 'Set up your workspace' : 'Configura tu espacio',
      justAName: en ? 'You just need a name to get started' : 'Solo necesitas un nombre para empezar',
      workspaceName: en ? 'Workspace name' : 'Nombre de tu workspace',
      workspacePlaceholder: en ? 'e.g. My Company, Dev Team...' : 'Ej: Mi Empresa, Equipo Dev...',
      workspaceHint: en ? 'This will be your workspace name' : 'Este será el nombre de tu espacio de trabajo',
      continueBtn: en ? 'Continue' : 'Continuar',
      firstProject: en ? 'Your first project' : 'Tu primer proyecto',
      projectPlaceholder: en ? 'e.g. Mobile App, API v2...' : 'Ej: App Mobile, API v2...',
      moreProjectsLater: en ? 'You can create more projects later' : 'Puedes crear más proyectos después',
      back: en ? 'Back' : 'Atrás',
      kanbanType: en ? 'Kanban board type' : 'Tipo de tablero Kanban',
      errorCreatingWorkspace: en ? 'Error creating workspace' : 'Error al crear el workspace',

      // ── Dark mode ──
      darkMode: en ? 'Dark mode' : 'Modo oscuro',
      lightMode: en ? 'Light mode' : 'Modo claro',

      // ── Project deletion ──
      deleteProject: en ? 'Delete project' : 'Eliminar proyecto',
      deleteConfirmProject: en ? 'Delete this project?' : '¿Eliminar este proyecto?',
      deleteProjectWarning: en ? 'All tasks, columns, and data in this project will be permanently deleted.' : 'Todas las tareas, columnas y datos de este proyecto se eliminarán permanentemente.',

      // ── Procrastination Quiz ──
      quizTitle: en ? 'Productivity Assessment' : 'Evaluación de Productividad',
      quizDescription: en ? 'Answer a few questions to understand your work patterns and get personalized tips to stay focused.' : 'Responde algunas preguntas para entender tus patrones de trabajo y obtener tips personalizados para mantener el enfoque.',
      quizStart: en ? 'Start assessment' : 'Iniciar evaluación',
      quizSkip: en ? 'Skip for now' : 'Saltar por ahora',
      quizFinish: en ? 'See results' : 'Ver resultados',
      quizGoToDashboard: en ? 'Go to dashboard' : 'Ir al dashboard',
      quizRetake: en ? 'Retake assessment' : 'Repetir evaluación',
      quizProductivityScore: en ? 'Productivity Score' : 'Puntuación de Productividad',
      quizLowRisk: en ? 'Low Risk' : 'Riesgo Bajo',
      quizModerateRisk: en ? 'Moderate Risk' : 'Riesgo Moderado',
      quizHighRisk: en ? 'High Risk' : 'Riesgo Alto',

      // ── Subtasks ──
      subtasks: en ? 'Subtasks' : 'Subtareas',
      addSubtask: en ? 'Add subtask' : 'Agregar subtarea',
      subtaskTitle: en ? 'Subtask title...' : 'Título de la subtarea...',
      subtaskProgress: en ? 'Subtask progress' : 'Progreso de subtareas',
      noSubtasks: en ? 'No subtasks yet' : 'Sin subtareas aún',
      maxDepthReached: en ? 'Maximum nesting depth reached' : 'Profundidad máxima alcanzada',
      subtaskOf: en ? 'Subtask of' : 'Subtarea de',
      parentTask: en ? 'Parent task' : 'Tarea padre',

      // ── Comments ──
      comments: en ? 'Comments' : 'Comentarios',
      addComment: en ? 'Add comment...' : 'Agregar comentario...',
      editComment: en ? 'Edit' : 'Editar',
      deleteComment: en ? 'Delete comment' : 'Eliminar comentario',
      commentEdited: en ? '(edited)' : '(editado)',
      actionItem: en ? 'Action item' : 'Elemento de acción',
      markResolved: en ? 'Mark resolved' : 'Marcar resuelto',
      markUnresolved: en ? 'Mark unresolved' : 'Marcar sin resolver',
      resolved: en ? 'Resolved' : 'Resuelto',
      assignTo: en ? 'Assign to' : 'Asignar a',
      mentions: en ? 'Mentions' : 'Menciones',
      actionItems: en ? 'Action Items' : 'Elementos de acción',
      myActionItems: en ? 'My action items' : 'Mis elementos de acción',
      noComments: en ? 'No comments yet' : 'Sin comentarios aún',
      writeComment: en ? 'Write a comment...' : 'Escribe un comentario...',

      // ── Time Tracking ──
      timeTracking: en ? 'Time Tracking' : 'Registro de Tiempo',
      timesheet: en ? 'Timesheet' : 'Hoja de Tiempo',
      startTimer: en ? 'Start timer' : 'Iniciar timer',
      stopTimer: en ? 'Stop timer' : 'Detener timer',
      timerRunning: en ? 'Timer running' : 'Timer activo',
      addTimeEntry: en ? 'Add time entry' : 'Agregar entrada de tiempo',
      editTimeEntry: en ? 'Edit time entry' : 'Editar entrada de tiempo',
      deleteTimeEntry: en ? 'Delete time entry' : 'Eliminar entrada de tiempo',
      startTime: en ? 'Start time' : 'Hora de inicio',
      endTime: en ? 'End time' : 'Hora de fin',
      durationMinutes: en ? 'Duration (min)' : 'Duración (min)',
      billable: en ? 'Billable' : 'Facturable',
      nonBillable: en ? 'Non-billable' : 'No facturable',
      manual: en ? 'Manual' : 'Manual',
      timer: en ? 'Timer' : 'Timer',
      totalTime: en ? 'Total time' : 'Tiempo total',
      thisWeek: en ? 'This week' : 'Esta semana',
      noTimeEntries: en ? 'No time entries' : 'Sin entradas de tiempo',
      hours: en ? 'hours' : 'horas',
      minutes: en ? 'minutes' : 'minutos',
      weeklyTotal: en ? 'Weekly total' : 'Total semanal',

      // ── Relationships (Phase 2) ──
      relationships: en ? 'Relationships' : 'Relaciones',
      addRelationship: en ? 'Add relationship' : 'Agregar relación',
      blocks: en ? 'Blocks' : 'Bloquea',
      blockedBy: en ? 'Blocked by' : 'Bloqueado por',
      relatesTo: en ? 'Relates to' : 'Relacionado con',
      duplicates: en ? 'Duplicates' : 'Duplica',
      duplicatedBy: en ? 'Duplicated by' : 'Duplicado por',
      noRelationships: en ? 'No relationships' : 'Sin relaciones',
      selectTask: en ? 'Select a task...' : 'Selecciona una tarea...',
      relationshipType: en ? 'Relationship type' : 'Tipo de relación',

      // ── Reassignment (Phase 2) ──
      reassign: en ? 'Reassign' : 'Reasignar',
      bulkReassign: en ? 'Bulk reassign' : 'Reasignación masiva',
      reassignFrom: en ? 'From user' : 'Del usuario',
      reassignTo: en ? 'To user' : 'Al usuario',
      reassignReason: en ? 'Reason (optional)' : 'Razón (opcional)',
      reassignHistory: en ? 'Reassignment history' : 'Historial de reasignación',
      tasksReassigned: en ? 'tasks reassigned' : 'tareas reasignadas',

      // ── Milestones (Phase 2) ──
      milestones: en ? 'Milestones' : 'Hitos',
      addMilestone: en ? 'Add milestone' : 'Agregar hito',
      targetDate: en ? 'Target date' : 'Fecha objetivo',
      milestoneCompleted: en ? 'Milestone completed' : 'Hito completado',
      noMilestones: en ? 'No milestones' : 'Sin hitos',

      // ── Roll-ups (Phase 2) ──
      rollups: en ? 'Overview' : 'Resumen',
      completionRate: en ? 'Completion rate' : 'Tasa de completado',
      openTasks: en ? 'Open tasks' : 'Tareas abiertas',
      avgCycleTime: en ? 'Avg cycle time' : 'Tiempo de ciclo promedio',
      projectHealth: en ? 'Project health' : 'Salud del proyecto',

      // ── Sprints (Phase 3) ──
      sprints: en ? 'Sprints' : 'Sprints',
      createSprint: en ? 'Create sprint' : 'Crear sprint',
      sprintName: en ? 'Sprint name' : 'Nombre del sprint',
      sprintGoal: en ? 'Sprint goal' : 'Objetivo del sprint',
      startDate: en ? 'Start date' : 'Fecha de inicio',
      endDate: en ? 'End date' : 'Fecha de fin',
      activeSprint: en ? 'Active sprint' : 'Sprint activo',
      plannedSprint: en ? 'Planned' : 'Planificado',
      completedSprint: en ? 'Completed' : 'Completado',
      startSprint: en ? 'Start sprint' : 'Iniciar sprint',
      completeSprint: en ? 'Complete sprint' : 'Completar sprint',
      noSprints: en ? 'No sprints' : 'Sin sprints',

      // ── Reports (Phase 3) ──
      reports: en ? 'Reports' : 'Reportes',
      burndownChart: en ? 'Burndown Chart' : 'Gráfico Burndown',
      velocityChart: en ? 'Velocity Chart' : 'Gráfico de Velocidad',
      cumulativeFlow: en ? 'Cumulative Flow' : 'Flujo Acumulado',
      cycleTime: en ? 'Cycle Time' : 'Tiempo de Ciclo',
      sprintReport: en ? 'Sprint Report' : 'Reporte de Sprint',

      // ── Goals & OKRs (Phase 3) ──
      goals: en ? 'Goals & OKRs' : 'Objetivos y OKRs',
      createGoal: en ? 'Create goal' : 'Crear objetivo',
      objective: en ? 'Objective' : 'Objetivo',
      keyResult: en ? 'Key Result' : 'Resultado Clave',
      goal: en ? 'Goal' : 'Meta',
      progress: en ? 'Progress' : 'Progreso',
      targetValue: en ? 'Target value' : 'Valor objetivo',
      currentValue: en ? 'Current value' : 'Valor actual',
      unit: en ? 'Unit' : 'Unidad',
      period: en ? 'Period' : 'Período',
      linkProject: en ? 'Link project' : 'Vincular proyecto',
      linkTask: en ? 'Link task' : 'Vincular tarea',
      noGoals: en ? 'No goals yet' : 'Sin objetivos aún',
      goalActive: en ? 'Active' : 'Activo',
      goalCompleted: en ? 'Completed' : 'Completado',
      goalCancelled: en ? 'Cancelled' : 'Cancelado',

      // ── Roadmap (Phase 3) ──
      roadmap: en ? 'Roadmap' : 'Roadmap',
      timeline: en ? 'Timeline' : 'Línea de tiempo',
      quarter: en ? 'Quarter' : 'Trimestre',
      week: en ? 'Week' : 'Semana',
      month: en ? 'Month' : 'Mes',
      projectsAndTasks: en ? 'Projects & Tasks' : 'Proyectos y Tareas',
      dependencies: en ? 'Dependencies' : 'Dependencias',
      expandAll: en ? 'Expand all' : 'Expandir todo',
      collapseAll: en ? 'Collapse all' : 'Colapsar todo',
      noTasksWithDates: en ? 'No tasks with dates' : 'Sin tareas con fechas',
      projectDependencies: en ? 'Project dependencies' : 'Dependencias de proyecto',
      addDependency: en ? 'Add dependency' : 'Agregar dependencia',
      dependsOn: en ? 'Depends on' : 'Depende de',
      noDependencies: en ? 'No dependencies' : 'Sin dependencias',
    }
  })

  return {
    language: currentLanguage,
    setLanguage,
    toggleLanguage,
    localizedTitle,
    localizedDescription,
    labels,
  }
}
