export type AppLanguage = 'es' | 'en' | 'ur'

/** Persisted language preference — shared across all components via module-level ref */
const currentLanguage = ref<AppLanguage>('es')
const _langInitialized = ref(false)

if (import.meta.client && !_langInitialized.value) {
  _langInitialized.value = true
  const saved = localStorage.getItem('focusflow_lang') as AppLanguage | null
  if (saved) {
    currentLanguage.value = saved
    if (saved === 'ur') {
      document.documentElement.dir = 'rtl'
      document.documentElement.lang = 'ur'
    }
  }
}

export function useLanguage() {
  function setLanguage(lang: AppLanguage) {
    currentLanguage.value = lang
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem('focusflow_lang', lang)
    }
    // Set document direction for RTL languages
    if (typeof document !== 'undefined') {
      document.documentElement.dir = lang === 'ur' ? 'rtl' : 'ltr'
      document.documentElement.lang = lang === 'ur' ? 'ur' : lang
    }
  }

  function toggleLanguage() {
    const cycle: Record<AppLanguage, AppLanguage> = { es: 'en', en: 'ur', ur: 'es' }
    setLanguage(cycle[currentLanguage.value])
  }

  /** Get the localized title for a task based on current language */
  function localizedTitle(task: { title: string; title_en?: string; translations?: Record<string, { title?: string; description?: string }> }): string {
    const lang = currentLanguage.value
    if (lang === 'en' && task.title_en) return task.title_en
    if (lang === 'ur' && task.translations?.ur?.title) return task.translations.ur.title
    // Fallback: if not Spanish and English translation exists, use that
    if (lang !== 'es' && task.title_en) return task.title_en
    return task.title
  }

  /** Get the localized description for a task based on current language */
  function localizedDescription(task: { description?: string; description_en?: string; translations?: Record<string, { title?: string; description?: string }> }): string {
    const lang = currentLanguage.value
    if (lang === 'en' && task.description_en) return task.description_en
    if (lang === 'ur' && task.translations?.ur?.description) return task.translations.ur.description
    if (lang !== 'es' && task.description_en) return task.description_en
    return task.description || ''
  }

  /** UI labels for common elements */
  const labels = computed(() => {
    const l = currentLanguage.value
    /** Helper: pick label by language */
    const t = (es: string, en: string, ur: string) => l === 'en' ? en : l === 'ur' ? ur : es

    return {
      // ── Common ──
      newTask: t('Nueva tarea', 'New task', 'نیا کام'),
      description: t('Descripción', 'Description', 'تفصیل'),
      priority: t('Prioridad', 'Priority', 'ترجیح'),
      dueDate: t('Fecha límite', 'Due date', 'آخری تاریخ'),
      column: t('Columna', 'Column', 'کالم'),
      estimation: t('Estimación (horas)', 'Estimation (hours)', 'اندازہ (گھنٹے)'),
      assigned: t('Asignados', 'Assigned', 'تفویض شدہ'),
      tags: t('Etiquetas', 'Tags', 'ٹیگز'),
      save: t('Guardar', 'Save', 'محفوظ کریں'),
      close: t('Cerrar', 'Close', 'بند کریں'),
      cancel: t('Cancelar', 'Cancel', 'منسوخ'),
      create: t('Crear tarea', 'Create task', 'کام بنائیں'),
      delete: t('Eliminar', 'Delete', 'حذف کریں'),
      deleteConfirm: t('¿Eliminar esta tarea?', 'Delete this task?', 'یہ کام حذف کریں؟'),
      addDescription: t('Agrega una descripción detallada...', 'Add a detailed description...', 'تفصیلی وضاحت شامل کریں...'),
      priorityLow: t('Baja', 'Low', 'کم'),
      priorityMedium: t('Media', 'Medium', 'درمیانی'),
      priorityHigh: t('Alta', 'High', 'زیادہ'),
      priorityCritical: t('Crítica', 'Critical', 'اہم'),
      import: t('Importar', 'Import', 'درآمد'),
      noTranslation: t('(Sin traducción disponible)', '(No translation available)', '(ترجمہ دستیاب نہیں)'),
      loading: t('Cargando...', 'Loading...', 'لوڈ ہو رہا ہے...'),
      error: t('Error', 'Error', 'خرابی'),
      confirm: t('Confirmar', 'Confirm', 'تصدیق'),
      optional: t('Opcional', 'Optional', 'اختیاری'),
      noResults: t('Sin resultados', 'No results', 'کوئی نتائج نہیں'),
      search: t('Buscar', 'Search', 'تلاش'),
      clear: t('Limpiar', 'Clear', 'صاف کریں'),
      selectAll: t('Seleccionar todos', 'Select all', 'سب منتخب کریں'),
      you: t('Tú', 'You', 'آپ'),
      role: t('Rol', 'Role', 'کردار'),
      email: t('Email', 'Email', 'ای میل'),

      // ── Dashboard ──
      goodMorning: t('Buenos días', 'Good morning', 'صبح بخیر'),
      goodAfternoon: t('Buenas tardes', 'Good afternoon', 'سہ پہر بخیر'),
      goodEvening: t('Buenas noches', 'Good evening', 'شام بخیر'),
      totalTasks: t('Tareas Totales', 'Total Tasks', 'کل کام'),
      inProgress: t('En Progreso', 'In Progress', 'جاری ہے'),
      completed: t('Completadas', 'Completed', 'مکمل'),
      projectSummary: t('Resumen de Proyectos', 'Project Summary', 'پروجیکٹ خلاصہ'),
      thisMonth: t('Este Mes', 'This Month', 'اس مہینے'),
      tokenUsage: t('Uso de Tokens AI', 'AI Token Usage', 'AI ٹوکن استعمال'),
      update: t('Actualizar', 'Update', 'اپ ڈیٹ'),
      pomodoroTimer: t('Pomodoro Timer', 'Pomodoro Timer', 'پومودورو ٹائمر'),
      focusSession: t('Sesión de enfoque', 'Focus session', 'توجہ کا وقت'),
      breakTime: t('Descanso', 'Break time', 'وقفہ'),
      start: t('Iniciar', 'Start', 'شروع'),
      pause: t('Pausar', 'Pause', 'روکیں'),
      reset: t('Reiniciar', 'Reset', 'دوبارہ شروع'),
      sessions: t('sesiones', 'sessions', 'سیشنز'),
      dayStreak: t('días seguidos', 'day streak', 'دن کی لکیر'),
      board: t('Tablero', 'Board', 'بورڈ'),
      viewAll: t('Ver todo', 'View all', 'سب دیکھیں'),
      name: t('Nombre', 'Name', 'نام'),
      project: t('Proyecto', 'Project', 'پروجیکٹ'),
      date: t('Fecha', 'Date', 'تاریخ'),
      status: t('Estado', 'Status', 'حالت'),
      deadline: t('Deadline', 'Deadline', 'آخری مہلت'),
      done: t('Hecho', 'Done', 'ہو گیا'),
      pending: t('Pendiente', 'Pending', 'زیر التوا'),
      all: t('Todos', 'All', 'سب'),
      filters: t('Filtros', 'Filters', 'فلٹرز'),
      projectRanking: t('Ranking de Proyectos', 'Project Ranking', 'پروجیکٹ درجہ بندی'),
      tasks: t('tareas', 'tasks', 'کام'),
      createProject: t('Crear proyecto', 'Create project', 'پروجیکٹ بنائیں'),
      noProjects: t('Sin proyectos aún', 'No projects yet', 'ابھی کوئی پروجیکٹ نہیں'),
      antiProcrastination: t('Coach Anti-Procrastinación', 'Anti-Procrastination Coach', 'تاخیر مخالف کوچ'),
      analyzeNow: t('Analizar ahora', 'Analyze now', 'ابھی تجزیہ کریں'),
      quickWins: t('Victorias rápidas', 'Quick Wins', 'فوری کامیابیاں'),
      dailyPlan: t('Plan del día', 'Daily Plan', 'روزانہ منصوبہ'),
      generatePlan: t('Generar plan con IA', 'Generate plan with AI', 'AI سے منصوبہ بنائیں'),
      focusTasks: t('Tareas de enfoque', 'Focus Tasks', 'توجہ کے کام'),
      viewProjects: t('Ver proyectos', 'View projects', 'پروجیکٹس دیکھیں'),
      newProject: t('Nuevo proyecto', 'New project', 'نیا پروجیکٹ'),
      general: t('General', 'General', 'عمومی'),
      daily: t('Diario', 'Daily', 'روزانہ'),
      today: t('Hoy', 'Today', 'آج'),
      vsYesterday: t('vs ayer', 'vs yesterday', 'کل کے مقابلے'),
      last7days: t('Últimos 7 días', 'Last 7 days', 'پچھلے 7 دن'),
      avgPerCall: t('Promedio por llamada', 'Avg per call', 'فی کال اوسط'),
      enableNotifications: t('Activar notificaciones', 'Enable notifications', 'اطلاعات فعال کریں'),
      tokensUsed: t('Tokens Usados', 'Tokens Used', 'استعمال شدہ ٹوکنز'),
      sessionsToday: t('Sesiones hoy', 'Sessions today', 'آج کے سیشنز'),
      streak: t('Racha', 'Streak', 'سلسلہ'),
      days: t('dias', 'days', 'دن'),
      focusedOn: t('Enfocado en', 'Focused on', 'توجہ مرکوز'),
      freeSession: t('Sesión libre', 'Free session', 'آزاد سیشن'),
      allTasks: t('Todas las tareas', 'All tasks', 'تمام کام'),
      noRecentTasks: t('No hay tareas recientes', 'No recent tasks', 'حالیہ کام نہیں'),
      noFilterResults: t('Sin resultados con estos filtros', 'No results with these filters', 'ان فلٹرز سے کوئی نتائج نہیں'),
      procrastinationRisk: t('Riesgo de procrastinación', 'Procrastination risk', 'تاخیر کا خطرہ'),
      todaysSessions: t('Sesiones de hoy', "Today's Sessions", 'آج کے سیشنز'),
      used: t('usado', 'used', 'استعمال شدہ'),
      analyzing: t('Analizando...', 'Analyzing...', 'تجزیہ ہو رہا ہے...'),
      whatsBlocking: t('¿Qué te está bloqueando hoy?', "What's blocking you today?", 'آج آپ کو کیا روک رہا ہے؟'),
      projectName: t('Nombre del proyecto', 'Project name', 'پروجیکٹ کا نام'),
      kanbanTemplate: t('Plantilla Kanban', 'Kanban Template', 'کنبان ٹیمپلیٹ'),

      // ── Navigation / Layout ──
      dashboard: t('Dashboard', 'Dashboard', 'ڈیش بورڈ'),
      projects: t('Proyectos', 'Projects', 'پروجیکٹس'),
      aiAgents: t('AI Agents', 'AI Agents', 'AI ایجنٹس'),
      files: t('Archivos', 'Files', 'فائلیں'),
      team: t('Equipo', 'Team', 'ٹیم'),
      roles: t('Roles', 'Roles', 'کردار'),
      rolesTitle: t('Permisos por Rol', 'Role Permissions', 'کردار کی اجازتیں'),
      rolesDescription: t('Personaliza lo que cada rol puede hacer en este workspace', 'Customize what each role can do in this workspace', 'اس ورک سپیس میں ہر کردار کیا کر سکتا ہے اسے حسب ضرورت بنائیں'),
      billing: t('Facturacion', 'Billing', 'بلنگ'),
      settings: t('Ajustes', 'Settings', 'ترتیبات'),
      home: t('Home', 'Home', 'ہوم'),
      more: t('Mas', 'More', 'مزید'),

      // ── Team page ──
      teamTitle: t('Equipo', 'Team', 'ٹیم'),
      membersCount: t('miembros en el workspace', 'members in workspace', 'ورک سپیس میں ممبران'),
      memberSingular: t('miembro', 'member', 'ممبر'),
      scheduleMeeting: t('Programar reunión', 'Schedule meeting', 'میٹنگ شیڈول کریں'),
      invite: t('Invitar', 'Invite', 'دعوت دیں'),
      upcomingMeetings: t('Próximas reuniones', 'Upcoming meetings', 'آنے والی میٹنگز'),
      join: t('Unirse', 'Join', 'شامل ہوں'),
      participants: t('participantes', 'participants', 'شرکاء'),
      loadingTeam: t('Cargando equipo...', 'Loading team...', 'ٹیم لوڈ ہو رہی ہے...'),
      noEmail: t('Sin email', 'No email', 'ای میل نہیں'),
      joined: t('Se unió', 'Joined', 'شامل ہوئے'),
      allProjects: t('Todos los proyectos', 'All projects', 'تمام پروجیکٹس'),
      noProjectAccess: t('Sin acceso a proyectos', 'No project access', 'پروجیکٹ تک رسائی نہیں'),
      addToProject: t('Añadir a proyecto', 'Add to project', 'پروجیکٹ میں شامل کریں'),
      manageAccess: t('Gestionar todos los accesos', 'Manage all access', 'تمام رسائی کا نظم کریں'),
      alreadyHasAll: t('Ya tiene acceso a todos', 'Already has access to all', 'پہلے سے سب تک رسائی ہے'),
      removeFromTeam: t('Remover del equipo', 'Remove from team', 'ٹیم سے ہٹائیں'),
      removeFromProject: t('Quitar de este proyecto', 'Remove from project', 'پروجیکٹ سے ہٹائیں'),
      noMembers: t('Sin miembros', 'No members', 'کوئی ممبر نہیں'),
      inviteTeam: t('Invita a tu equipo para colaborar', 'Invite your team to collaborate', 'تعاون کے لیے اپنی ٹیم کو مدعو کریں'),
      inviteMember: t('Invitar miembro', 'Invite member', 'ممبر کو مدعو کریں'),
      inviteDesc: t('El usuario debe tener una cuenta en FocusFlow', 'The user must have a FocusFlow account', 'صارف کے پاس FocusFlow اکاؤنٹ ہونا ضروری ہے'),
      pendingInvitations: t('Invitaciones pendientes', 'Pending invitations', 'زیر التوا دعوت نامے'),
      pendingInvite: t('Invitacion pendiente', 'Pending invite', 'زیر التوا دعوت'),
      cancelInvite: t('Cancelar invitacion', 'Cancel invitation', 'دعوت منسوخ کریں'),
      confirmCancelInvite: t('Cancelar invitacion para {email}?', 'Cancel invitation for {email}?', '{email} کے لیے دعوت منسوخ کریں؟'),
      userEmail: t('Email del usuario', 'User email', 'صارف کا ای میل'),
      projectAccess: t('Acceso a proyectos', 'Project access', 'پروجیکٹ تک رسائی'),
      adminAutoAccess: t('Los roles admin+ tienen acceso automático a todos los proyectos', 'Admin+ roles have automatic access to all projects', 'ایڈمن+ کردار کو تمام پروجیکٹس تک خودکار رسائی ہے'),
      addedToTeam: t('agregado al equipo', 'added to team', 'ٹیم میں شامل کیا گیا'),
      errorInviting: t('Error al invitar', 'Error inviting', 'دعوت میں خرابی'),
      errorChangingRole: t('Error al cambiar rol', 'Error changing role', 'کردار تبدیل کرنے میں خرابی'),
      confirmRemoveMember: t('¿Remover a "{name}" del equipo?', 'Remove "{name}" from team?', '"{name}" کو ٹیم سے ہٹائیں؟'),
      errorRemovingMember: t('Error al remover miembro', 'Error removing member', 'ممبر ہٹانے میں خرابی'),
      errorAddingProject: t('Error al añadir proyecto', 'Error adding project', 'پروجیکٹ شامل کرنے میں خرابی'),
      errorRemovingProject: t('Error al quitar proyecto', 'Error removing project', 'پروجیکٹ ہٹانے میں خرابی'),
      errorUpdatingAccess: t('Error al actualizar acceso', 'Error updating access', 'رسائی اپ ڈیٹ میں خرابی'),
      member: t('Miembro', 'Member', 'ممبر'),
      viewer: t('Viewer', 'Viewer', 'ناظر'),
      admin: t('Admin', 'Admin', 'ایڈمن'),
      owner: t('Owner', 'Owner', 'مالک'),
      superadmin: t('Superadmin', 'Superadmin', 'سپر ایڈمن'),

      // ── Procrastination metrics ──
      procrastinationMetrics: t('Métricas de productividad', 'Productivity metrics', 'پیداواری میٹرکس'),
      showMetrics: t('Mostrar métricas', 'Show metrics', 'میٹرکس دکھائیں'),
      hideMetrics: t('Ocultar métricas', 'Hide metrics', 'میٹرکس چھپائیں'),
      procrastinationIndex: t('Índice de procrastinación', 'Procrastination Index', 'تاخیر کا اشاریہ'),
      procrastinationIndexDesc: t('Puntaje ponderado del comportamiento con tareas (0 = ideal, 100 = alta procrastinación)', 'Weighted score from task behavior (0 = ideal, 100 = high procrastination)', 'کام کے رویے سے وزنی سکور (0 = مثالی، 100 = زیادہ تاخیر)'),
      overdueRate: t('Tasa de atraso', 'Overdue Rate', 'تاخیر کی شرح'),
      overdueRateDesc: t('Porcentaje de tareas pasadas de fecha que aún no se completan', 'Percentage of tasks past due date still not completed', 'مقررہ تاریخ گزرنے کے بعد نامکمل کاموں کا فیصد'),
      lateCompletionRate: t('Completado tardío', 'Late Completion', 'تاخیر سے مکمل'),
      lateCompletionRateDesc: t('Porcentaje de tareas completadas después de la fecha límite', 'Percentage of tasks completed after the due date', 'آخری تاریخ کے بعد مکمل ہونے والے کاموں کا فیصد'),
      stagnationScore: t('Estancamiento', 'Stagnation', 'جمود'),
      stagnationScoreDesc: t('Promedio de inactividad en tareas abiertas (30+ días = puntaje máximo)', 'Average inactivity on open tasks (30+ days = max score)', 'کھلے کاموں پر اوسط غیر فعالیت (30+ دن = زیادہ سے زیادہ سکور)'),
      effortGap: t('Brecha de esfuerzo', 'Effort Gap', 'محنت کا فرق'),
      effortGapDesc: t('Diferencia entre horas estimadas y registradas', 'Difference between estimated and tracked hours', 'تخمینی اور ریکارڈ شدہ گھنٹوں میں فرق'),
      quizScore: t('Puntaje del quiz', 'Quiz Score', 'کوئز سکور'),
      quizScoreDesc: t('Resultado del quiz de autoevaluación de procrastinación', 'Self-assessment procrastination quiz result', 'خود تشخیصی تاخیر کوئز کا نتیجہ'),
      noTaskData: t('Sin datos de tareas', 'No task data', 'کام کا ڈیٹا نہیں'),
      lowRisk: t('Bajo', 'Low', 'کم'),
      moderateRisk: t('Moderado', 'Moderate', 'درمیانہ'),
      highRisk: t('Alto', 'High', 'زیادہ'),
      tasksTracked: t('tareas rastreadas', 'tasks tracked', 'ٹریک شدہ کام'),
      loadingMetrics: t('Cargando métricas...', 'Loading metrics...', 'میٹرکس لوڈ ہو رہے ہیں...'),

      // ── Kanban ──
      aiSuggestions: t('AI Sugerencias', 'AI Suggestions', 'AI تجاویز'),
      createTask: t('Crear tarea', 'Create task', 'کام بنائیں'),
      loadingBoard: t('Cargando tablero...', 'Loading board...', 'بورڈ لوڈ ہو رہا ہے...'),
      editColumn: t('Editar columna', 'Edit column', 'کالم میں ترمیم'),
      deleteColumn: t('Eliminar columna', 'Delete column', 'کالم حذف کریں'),
      columnName: t('Nombre de la columna', 'Column name', 'کالم کا نام'),
      assignedTo: t('Asignado a', 'Assigned to', 'تفویض کیا گیا'),
      noTasksMobile: t('Sin tareas', 'No tasks', 'کوئی کام نہیں'),
      noTasksDrag: t('Arrastra tareas aquí', 'Drag tasks here', 'کام یہاں گھسیٹیں'),
      createAllOnBoard: t('Crear todas en el tablero', 'Create all on board', 'بورڈ پر سب بنائیں'),
      dueToday: t('Vencen Hoy', 'Due Today', 'آج واجب'),
      startPomodoro: t('Iniciar Pomodoro', 'Start Pomodoro', 'پومودورو شروع کریں'),
      improveWithAI: t('Mejorar con AI', 'Improve with AI', 'AI سے بہتر بنائیں'),
      deleteTask: t('Eliminar tarea', 'Delete task', 'کام حذف کریں'),
      noEstimate: t('Sin estimación', 'No estimate', 'کوئی اندازہ نہیں'),
      whatToDo: t('¿Qué hay que hacer?', 'What needs to be done?', 'کیا کرنا ہے؟'),
      describeTask: t('Describe la tarea...', 'Describe the task...', 'کام کی وضاحت کریں...'),
      addToBoard: t('Agrega una tarea al tablero', 'Add task to board', 'بورڈ میں کام شامل کریں'),
      tagsSeparated: t('Etiquetas (separadas por coma)', 'Tags (comma separated)', 'ٹیگز (کوما سے الگ)'),
      tagPlaceholder: t('bug, frontend, urgente...', 'bug, frontend, urgent...', 'بگ، فرنٹ اینڈ، فوری...'),
      errorCreating: t('Error al crear tarea', 'Error creating task', 'کام بنانے میں خرابی'),
      title: t('Título', 'Title', 'عنوان'),

      // ── Agents ──
      agentsDesc: t('Agentes de gestión de tareas y documentación con memoria por sesión', 'Task management and documentation agents with session memory', 'سیشن میموری کے ساتھ کام کے انتظام اور دستاویزات کے ایجنٹس'),
      selectProject: t('Selecciona un proyecto...', 'Select a project...', 'پروجیکٹ منتخب کریں...'),
      noAIPermission: t('No tienes permisos para usar los agentes AI', 'You don\'t have permission to use AI agents', 'آپ کو AI ایجنٹس استعمال کرنے کی اجازت نہیں'),
      selectProjectFirst: t('Selecciona un proyecto para ejecutar los agentes', 'Select a project to run agents', 'ایجنٹس چلانے کے لیے پروجیکٹ منتخب کریں'),
      taskManagement: t('Gestión de Tareas', 'Task Management', 'کام کا انتظام'),
      documentation: t('Documentación', 'Documentation', 'دستاویزات'),
      running: t('Ejecutando...', 'Running...', 'چل رہا ہے...'),
      generating: t('Generando...', 'Generating...', 'بن رہا ہے...'),
      generateDocs: t('Generar documentación', 'Generate documentation', 'دستاویزات بنائیں'),
      improveTasks: t('Mejorar tareas', 'Improve tasks', 'کام بہتر بنائیں'),
      analyzeLoad: t('Analizar carga', 'Analyze load', 'بوجھ کا تجزیہ'),
      execute: t('Ejecutar', 'Execute', 'عمل کریں'),
      tasksCreated: t('tareas creadas', 'tasks created', 'بنائے گئے کام'),
      tasksImproved: t('tareas mejoradas', 'tasks improved', 'بہتر کیے گئے کام'),
      health: t('Salud:', 'Health:', 'صحت:'),
      estimatedHours: t('h estimadas', 'h estimated', 'گھنٹے تخمینی'),
      bottlenecks: t('Cuellos de botella', 'Bottlenecks', 'رکاوٹیں'),
      recommendations: t('Recomendaciones', 'Recommendations', 'سفارشات'),
      sections: t('Secciones', 'Sections', 'حصے'),
      moreEllipsis: t('más...', 'more...', 'مزید...'),
      savedMd: t('.md guardado', '.md saved', '.md محفوظ ہو گیا'),

      // ── Projects page ──
      totalProjects: t('Proyectos Totales', 'Total Projects', 'کل پروجیکٹس'),
      sprintBoard: t('Tablero — Tareas del Sprint', 'Board — Sprint Tasks', 'بورڈ — سپرنٹ کے کام'),
      workspaceNotFound: t('Workspace no encontrado', 'Workspace not found', 'ورک سپیس نہیں ملا'),
      createWorkspaceFirst: t('Necesitas crear un workspace primero', 'You need to create a workspace first', 'پہلے ورک سپیس بنانا ضروری ہے'),
      createWorkspace: t('Crear workspace', 'Create workspace', 'ورک سپیس بنائیں'),
      noProjectsDesc: t('Crea tu primer proyecto para organizar tareas en un tablero Kanban', 'Create your first project to organize tasks in a Kanban board', 'کنبان بورڈ میں کام منظم کرنے کے لیے اپنا پہلا پروجیکٹ بنائیں'),
      createFirstProject: t('Crear primer proyecto', 'Create first project', 'پہلا پروجیکٹ بنائیں'),
      configureProject: t('Configura los detalles de tu proyecto', 'Configure your project details', 'اپنے پروجیکٹ کی تفصیلات مرتب کریں'),
      projectNamePlaceholder: t('Ej: App Mobile, API v2...', 'e.g. Mobile App, API v2...', 'مثلاً: موبائل ایپ، API v2...'),
      descriptionOptional: t('Descripción (opcional)', 'Description (optional)', 'تفصیل (اختیاری)'),
      whatIsProject: t('¿De qué trata este proyecto?', 'What is this project about?', 'یہ پروجیکٹ کس بارے میں ہے؟'),
      columns: t('columnas', 'columns', 'کالم'),
      active: t('Activo', 'Active', 'فعال'),
      planning: t('Planificación', 'Planning', 'منصوبہ بندی'),
      review: t('Revisión', 'Review', 'جائزہ'),
      paused: t('Pausado', 'Paused', 'موقوف'),

      // ── Files page ──
      filesTitle: t('Archivos', 'Files', 'فائلیں'),
      filesDesc: t('Gestiona los documentos de tu workspace', 'Manage your workspace documents', 'اپنے ورک سپیس کی دستاویزات کا نظم کریں'),
      uploadFile: t('Subir archivo', 'Upload file', 'فائل اپ لوڈ کریں'),
      loadingFiles: t('Cargando archivos...', 'Loading files...', 'فائلیں لوڈ ہو رہی ہیں...'),
      noFiles: t('Sin archivos', 'No files', 'کوئی فائلیں نہیں'),
      noFilesDesc: t('Sube archivos o genera documentos con AI para verlos aquí', 'Upload files or generate documents with AI to see them here', 'یہاں دیکھنے کے لیے فائلیں اپ لوڈ کریں یا AI سے دستاویزات بنائیں'),
      folders: t('Carpetas', 'Folders', 'فولڈرز'),
      download: t('Descargar', 'Download', 'ڈاؤن لوڈ'),
      confirmDeleteFile: t('¿Eliminar "{name}"?', 'Delete "{name}"?', '"{name}" حذف کریں؟'),
      errorUploading: t('Error al subir archivo', 'Error uploading file', 'فائل اپ لوڈ میں خرابی'),
      errorDownloading: t('Error al descargar', 'Error downloading', 'ڈاؤن لوڈ میں خرابی'),
      errorDeletingFile: t('Error al eliminar archivo. Intenta de nuevo.', 'Error deleting file. Try again.', 'فائل حذف کرنے میں خرابی۔ دوبارہ کوشش کریں۔'),

      // ── Settings page ──
      settingsTitle: t('Ajustes', 'Settings', 'ترتیبات'),
      workspaceConfig: t('Configuración general del espacio de trabajo', 'General workspace configuration', 'ورک سپیس کی عمومی ترتیب'),
      slugUrl: t('Slug (URL)', 'Slug (URL)', 'سلگ (URL)'),
      saveChanges: t('Guardar cambios', 'Save changes', 'تبدیلیاں محفوظ کریں'),
      savedSuccess: t('Guardado correctamente', 'Saved successfully', 'کامیابی سے محفوظ ہو گیا'),
      yourProfile: t('Tu perfil', 'Your profile', 'آپ کا پروفائل'),
      accountInfo: t('Información de tu cuenta', 'Your account information', 'آپ کے اکاؤنٹ کی معلومات'),
      dangerZone: t('Zona de peligro', 'Danger zone', 'خطرناک علاقہ'),
      irreversibleActions: t('Acciones irreversibles', 'Irreversible actions', 'ناقابل واپسی اقدامات'),
      logout: t('Cerrar sesión', 'Log out', 'لاگ آؤٹ'),
      logoutDesc: t('Salir de tu cuenta en este dispositivo', 'Sign out from your account on this device', 'اس ڈیوائس سے اپنے اکاؤنٹ سے باہر نکلیں'),

      // ── Meeting modal ──
      scheduleMeetingTitle: t('Programar reunión', 'Schedule meeting', 'میٹنگ شیڈول کریں'),
      meetingTitle: t('Título de la reunión', 'Meeting title', 'میٹنگ کا عنوان'),
      meetingTitlePlaceholder: t('Ej: Sprint Review, Daily Standup...', 'e.g. Sprint Review, Daily Standup...', 'مثلاً: سپرنٹ ریویو، ڈیلی اسٹینڈ اپ...'),
      meetingAgenda: t('Agenda de la reunión...', 'Meeting agenda...', 'میٹنگ ایجنڈا...'),
      dateTime: t('Fecha y hora', 'Date and time', 'تاریخ اور وقت'),
      duration: t('Duración', 'Duration', 'دورانیہ'),
      projectOptional: t('Proyecto (opcional)', 'Project (optional)', 'پروجیکٹ (اختیاری)'),
      noProjectOption: t('Sin proyecto', 'No project', 'کوئی پروجیکٹ نہیں'),
      attendees: t('Participantes', 'Attendees', 'شرکاء'),
      attendeesSelected: t('participante(s) seleccionado(s) — recibirán email con enlace de Google Meet', 'attendee(s) selected — they will receive an email with Google Meet link', 'شرکاء منتخب — انہیں Google Meet لنک کے ساتھ ای میل ملے گا'),
      meetAutoGenerate: t('Se generará automáticamente un enlace de Meet', 'A Meet link will be generated automatically', 'Meet لنک خود بخود بنایا جائے گا'),
      meetingScheduled: t('Reunión programada', 'Meeting scheduled', 'میٹنگ شیڈول ہو گئی'),
      invitationsSent: t('Se enviaron invitaciones por email a', 'Email invitations sent to', 'ای میل دعوت نامے بھیجے گئے'),
      schedule: t('Programar', 'Schedule', 'شیڈول کریں'),
      errorScheduling: t('Error al programar reunión', 'Error scheduling meeting', 'میٹنگ شیڈول کرنے میں خرابی'),
      hour1: t('1 hora', '1 hour', '1 گھنٹہ'),
      hours1_5: t('1.5 horas', '1.5 hours', 'ڈیڑھ گھنٹے'),
      hours2: t('2 horas', '2 hours', '2 گھنٹے'),

      // ── Import modal ──
      importTasks: t('Importar tareas', 'Import tasks', 'کام درآمد کریں'),
      compatiblePlatforms: t('Plataformas compatibles', 'Compatible platforms', 'ہم آہنگ پلیٹ فارمز'),
      genericCsv: t('CSV genérico', 'Generic CSV', 'عام CSV'),
      targetColumn: t('Columna destino (por defecto)', 'Target column (default)', 'ہدف کالم (پہلے سے طے شدہ)'),
      firstColumn: t('Primera columna', 'First column', 'پہلا کالم'),
      mapColumnsLabel: t('Mapear status/columnas del CSV a las columnas del proyecto', 'Map CSV status/columns to project columns', 'CSV اسٹیٹس/کالم کو پروجیکٹ کالم سے جوڑیں'),
      pasteOrUpload: t('Pegar CSV o subir archivo', 'Paste CSV or upload file', 'CSV پیسٹ کریں یا فائل اپ لوڈ کریں'),
      uploadCsv: t('Subir archivo .csv', 'Upload .csv file', '.csv فائل اپ لوڈ کریں'),
      rowsDetected: t('filas detectadas', 'rows detected', 'قطاریں ملیں'),
      dropFileHere: t('Suelta el archivo aquí', 'Drop the file here', 'فائل یہاں چھوڑیں'),
      dragDropCsv: t('Arrastra un archivo CSV aquí', 'Drag a CSV file here', 'CSV فائل یہاں گھسیٹیں'),
      orClickBrowse: t('o haz clic para buscar', 'or click to browse', 'یا براؤز کرنے کے لیے کلک کریں'),
      orPasteBelow: t('o pega abajo', 'or paste below', 'یا نیچے پیسٹ کریں'),
      replaceFile: t('Reemplazar archivo', 'Replace file', 'فائل بدلیں'),
      preview: t('Vista previa:', 'Preview:', 'پیش نظارہ:'),
      moreTasks: t('tareas más...', 'more tasks...', 'مزید کام...'),
      tasksImported: t('tareas importadas correctamente', 'tasks imported successfully', 'کام کامیابی سے درآمد ہوئے'),
      formatDetected: t('Formato detectado:', 'Format detected:', 'فارمیٹ شناخت ہوا:'),
      errorImporting: t('Error al importar', 'Error importing', 'درآمد میں خرابی'),

      // ── Attachments ──
      attachments: t('Adjuntos', 'Attachments', 'منسلکات'),
      addAttachment: t('+ Agregar', '+ Add', '+ شامل کریں'),
      dragFilesHere: t('Arrastra archivos aquí o', 'Drag files here or', 'فائلیں یہاں گھسیٹیں یا'),
      selectFiles: t('selecciona', 'select', 'منتخب کریں'),
      uploading: t('Subiendo...', 'Uploading...', 'اپ لوڈ ہو رہا ہے...'),

      // ── Labels ──
      labels: t('Labels', 'Labels', 'لیبلز'),
      labelName: t('Nombre del label', 'Label name', 'لیبل کا نام'),
      createLabel: t('+ Crear label', '+ Create label', '+ لیبل بنائیں'),
      suggestionsLabel: t('Sugerencias:', 'Suggestions:', 'تجاویز:'),
      urgent: t('Urgente', 'Urgent', 'فوری'),

      // ── Notifications ──
      notifications: t('Notificaciones', 'Notifications', 'اطلاعات'),
      markAllRead: t('Marcar todo leído', 'Mark all read', 'سب پڑھا ہوا نشان لگائیں'),
      noNotifications: t('Sin notificaciones', 'No notifications', 'کوئی اطلاعات نہیں'),
      now: t('ahora', 'now', 'ابھی'),
      minutesAgo: t('m', 'm ago', 'منٹ پہلے'),
      hoursAgo: t('h', 'h ago', 'گھنٹے پہلے'),
      daysAgo: t('d', 'd ago', 'دن پہلے'),

      // ── Auth pages ──
      createYourAccount: t('Crea tu cuenta', 'Create your account', 'اپنا اکاؤنٹ بنائیں'),
      startManaging: t('Empieza a gestionar tus proyectos hoy', 'Start managing your projects today', 'آج ہی اپنے پروجیکٹس کا نظم شروع کریں'),
      password: t('Contraseña', 'Password', 'پاس ورڈ'),
      confirmPassword: t('Confirmar contraseña', 'Confirm password', 'پاس ورڈ کی تصدیق'),
      minChars: t('Mínimo 6 caracteres', 'At least 6 characters', 'کم از کم 6 حروف'),
      repeatPassword: t('Repetir contraseña', 'Repeat password', 'پاس ورڈ دہرائیں'),
      createAccountBtn: t('Crear cuenta', 'Create account', 'اکاؤنٹ بنائیں'),
      orContinueWith: t('o continua con', 'or continue with', 'یا جاری رکھیں'),
      connectWallet: t('Web3 Wallet', 'Web3 Wallet', 'Web3 والٹ'),
      installWallet: t('Instala MetaMask o una wallet Web3 compatible para continuar.', 'Install MetaMask or a compatible Web3 wallet to continue.', 'جاری رکھنے کے لیے MetaMask یا ہم آہنگ Web3 والٹ انسٹال کریں۔'),
      alreadyHaveAccount: t('¿Ya tienes cuenta?', 'Already have an account?', 'پہلے سے اکاؤنٹ ہے؟'),
      signIn: t('Inicia sesión', 'Sign in', 'سائن ان'),
      welcomeBack: t('Bienvenido de nuevo', 'Welcome back', 'واپسی پر خوش آمدید'),
      loginSubtitle: t('Inicia sesión para continuar con tus proyectos', 'Sign in to continue with your projects', 'اپنے پروجیکٹس جاری رکھنے کے لیے سائن ان کریں'),
      enterPassword: t('Ingresa tu contraseña', 'Enter your password', 'اپنا پاس ورڈ درج کریں'),
      signInBtn: t('Iniciar sesión', 'Sign in', 'سائن ان کریں'),
      noAccount: t('¿No tienes cuenta?', "Don't have an account?", 'اکاؤنٹ نہیں ہے؟'),
      passwordsMismatch: t('Las contraseñas no coinciden', 'Passwords do not match', 'پاس ورڈ مماثل نہیں'),
      passwordTooShort: t('La contraseña debe tener al menos 6 caracteres', 'Password must be at least 6 characters', 'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے'),
      registerError: t('Error al registrarse', 'Error signing up', 'رجسٹریشن میں خرابی'),
      loginError: t('Email o contraseña incorrectos', 'Wrong email or password', 'غلط ای میل یا پاس ورڈ'),
      googleError: t('Error con Google', 'Error with Google', 'Google میں خرابی'),

      // ── Onboarding ──
      setupWorkspace: t('Configura tu espacio', 'Set up your workspace', 'اپنا ورک سپیس ترتیب دیں'),
      justAName: t('Solo necesitas un nombre para empezar', 'You just need a name to get started', 'شروع کرنے کے لیے صرف ایک نام چاہیے'),
      workspaceName: t('Nombre de tu workspace', 'Workspace name', 'ورک سپیس کا نام'),
      workspacePlaceholder: t('Ej: Mi Empresa, Equipo Dev...', 'e.g. My Company, Dev Team...', 'مثلاً: میری کمپنی، ڈیو ٹیم...'),
      workspaceHint: t('Este será el nombre de tu espacio de trabajo', 'This will be your workspace name', 'یہ آپ کے ورک سپیس کا نام ہوگا'),
      continueBtn: t('Continuar', 'Continue', 'جاری رکھیں'),
      firstProject: t('Tu primer proyecto', 'Your first project', 'آپ کا پہلا پروجیکٹ'),
      projectPlaceholder: t('Ej: App Mobile, API v2...', 'e.g. Mobile App, API v2...', 'مثلاً: موبائل ایپ، API v2...'),
      moreProjectsLater: t('Puedes crear más proyectos después', 'You can create more projects later', 'آپ بعد میں مزید پروجیکٹس بنا سکتے ہیں'),
      back: t('Atrás', 'Back', 'واپس'),
      kanbanType: t('Tipo de tablero Kanban', 'Kanban board type', 'کنبان بورڈ کی قسم'),
      errorCreatingWorkspace: t('Error al crear el workspace', 'Error creating workspace', 'ورک سپیس بنانے میں خرابی'),

      // ── Dark mode ──
      darkMode: t('Modo oscuro', 'Dark mode', 'ڈارک موڈ'),
      lightMode: t('Modo claro', 'Light mode', 'لائٹ موڈ'),

      // ── Project deletion ──
      deleteProject: t('Eliminar proyecto', 'Delete project', 'پروجیکٹ حذف کریں'),
      deleteConfirmProject: t('¿Eliminar este proyecto?', 'Delete this project?', 'یہ پروجیکٹ حذف کریں؟'),
      deleteProjectWarning: t('Todas las tareas, columnas y datos de este proyecto se eliminarán permanentemente.', 'All tasks, columns, and data in this project will be permanently deleted.', 'اس پروجیکٹ کے تمام کام، کالم اور ڈیٹا مستقل طور پر حذف ہو جائیں گے۔'),

      // ── Procrastination Quiz ──
      quizTitle: t('Evaluación de Productividad', 'Productivity Assessment', 'پیداواری جائزہ'),
      quizDescription: t('Responde algunas preguntas para entender tus patrones de trabajo y obtener tips personalizados para mantener el enfoque.', 'Answer a few questions to understand your work patterns and get personalized tips to stay focused.', 'اپنے کام کے انداز کو سمجھنے اور توجہ مرکوز رکھنے کے لیے ذاتی تجاویز حاصل کرنے کے لیے چند سوالات کا جواب دیں۔'),
      quizStart: t('Iniciar evaluación', 'Start assessment', 'جائزہ شروع کریں'),
      quizSkip: t('Saltar por ahora', 'Skip for now', 'ابھی چھوڑیں'),
      quizFinish: t('Ver resultados', 'See results', 'نتائج دیکھیں'),
      quizGoToDashboard: t('Ir al dashboard', 'Go to dashboard', 'ڈیش بورڈ پر جائیں'),
      quizRetake: t('Repetir evaluación', 'Retake assessment', 'جائزہ دوبارہ لیں'),
      quizProductivityScore: t('Puntuación de Productividad', 'Productivity Score', 'پیداواری سکور'),
      quizLowRisk: t('Riesgo Bajo', 'Low Risk', 'کم خطرہ'),
      quizModerateRisk: t('Riesgo Moderado', 'Moderate Risk', 'درمیانہ خطرہ'),
      quizHighRisk: t('Riesgo Alto', 'High Risk', 'زیادہ خطرہ'),

      // ── Subtasks ──
      subtasks: t('Subtareas', 'Subtasks', 'ذیلی کام'),
      addSubtask: t('Agregar subtarea', 'Add subtask', 'ذیلی کام شامل کریں'),
      subtaskTitle: t('Título de la subtarea...', 'Subtask title...', 'ذیلی کام کا عنوان...'),
      subtaskProgress: t('Progreso de subtareas', 'Subtask progress', 'ذیلی کاموں کی پیشرفت'),
      noSubtasks: t('Sin subtareas aún', 'No subtasks yet', 'ابھی کوئی ذیلی کام نہیں'),
      maxDepthReached: t('Profundidad máxima alcanzada', 'Maximum nesting depth reached', 'زیادہ سے زیادہ گہرائی تک پہنچ گئی'),
      subtaskOf: t('Subtarea de', 'Subtask of', 'ذیلی کام'),
      parentTask: t('Tarea padre', 'Parent task', 'بنیادی کام'),

      // ── Comments ──
      comments: t('Comentarios', 'Comments', 'تبصرے'),
      addComment: t('Agregar comentario...', 'Add comment...', 'تبصرہ شامل کریں...'),
      editComment: t('Editar', 'Edit', 'ترمیم'),
      deleteComment: t('Eliminar comentario', 'Delete comment', 'تبصرہ حذف کریں'),
      commentEdited: t('(editado)', '(edited)', '(ترمیم شدہ)'),
      actionItem: t('Elemento de acción', 'Action item', 'عمل کی شے'),
      markResolved: t('Marcar resuelto', 'Mark resolved', 'حل شدہ نشان لگائیں'),
      markUnresolved: t('Marcar sin resolver', 'Mark unresolved', 'غیر حل شدہ نشان لگائیں'),
      resolved: t('Resuelto', 'Resolved', 'حل شدہ'),
      assignTo: t('Asignar a', 'Assign to', 'تفویض کریں'),
      mentions: t('Menciones', 'Mentions', 'حوالے'),
      actionItems: t('Elementos de acción', 'Action Items', 'عمل کی اشیاء'),
      myActionItems: t('Mis elementos de acción', 'My action items', 'میری عمل کی اشیاء'),
      noComments: t('Sin comentarios aún', 'No comments yet', 'ابھی کوئی تبصرے نہیں'),
      writeComment: t('Escribe un comentario...', 'Write a comment...', 'تبصرہ لکھیں...'),

      // ── Time Tracking ──
      timeTracking: t('Registro de Tiempo', 'Time Tracking', 'وقت کی ریکارڈنگ'),
      timesheet: t('Hoja de Tiempo', 'Timesheet', 'ٹائم شیٹ'),
      startTimer: t('Iniciar timer', 'Start timer', 'ٹائمر شروع کریں'),
      stopTimer: t('Detener timer', 'Stop timer', 'ٹائمر بند کریں'),
      timerRunning: t('Timer activo', 'Timer running', 'ٹائمر چل رہا ہے'),
      addTimeEntry: t('Agregar entrada de tiempo', 'Add time entry', 'وقت کا اندراج شامل کریں'),
      editTimeEntry: t('Editar entrada de tiempo', 'Edit time entry', 'وقت کے اندراج میں ترمیم'),
      deleteTimeEntry: t('Eliminar entrada de tiempo', 'Delete time entry', 'وقت کا اندراج حذف کریں'),
      startTime: t('Hora de inicio', 'Start time', 'شروع کا وقت'),
      endTime: t('Hora de fin', 'End time', 'اختتام کا وقت'),
      durationMinutes: t('Duración (min)', 'Duration (min)', 'دورانیہ (منٹ)'),
      billable: t('Facturable', 'Billable', 'قابل بل'),
      nonBillable: t('No facturable', 'Non-billable', 'غیر قابل بل'),
      manual: t('Manual', 'Manual', 'دستی'),
      timer: t('Timer', 'Timer', 'ٹائمر'),
      totalTime: t('Tiempo total', 'Total time', 'کل وقت'),
      thisWeek: t('Esta semana', 'This week', 'اس ہفتے'),
      noTimeEntries: t('Sin entradas de tiempo', 'No time entries', 'وقت کے اندراجات نہیں'),
      hours: t('horas', 'hours', 'گھنٹے'),
      minutes: t('minutos', 'minutes', 'منٹ'),
      weeklyTotal: t('Total semanal', 'Weekly total', 'ہفتہ وار کل'),

      // ── Relationships (Phase 2) ──
      relationships: t('Relaciones', 'Relationships', 'تعلقات'),
      addRelationship: t('Agregar relación', 'Add relationship', 'تعلق شامل کریں'),
      blocks: t('Bloquea', 'Blocks', 'روکتا ہے'),
      blockedBy: t('Bloqueado por', 'Blocked by', 'روکا ہوا'),
      relatesTo: t('Relacionado con', 'Relates to', 'متعلق ہے'),
      duplicates: t('Duplica', 'Duplicates', 'نقل'),
      duplicatedBy: t('Duplicado por', 'Duplicated by', 'نقل کیا گیا'),
      noRelationships: t('Sin relaciones', 'No relationships', 'کوئی تعلقات نہیں'),
      selectTask: t('Selecciona una tarea...', 'Select a task...', 'کام منتخب کریں...'),
      relationshipType: t('Tipo de relación', 'Relationship type', 'تعلق کی قسم'),

      // ── Reassignment (Phase 2) ──
      reassign: t('Reasignar', 'Reassign', 'دوبارہ تفویض'),
      bulkReassign: t('Reasignación masiva', 'Bulk reassign', 'بڑے پیمانے پر تفویض'),
      reassignFrom: t('Del usuario', 'From user', 'صارف سے'),
      reassignTo: t('Al usuario', 'To user', 'صارف کو'),
      reassignReason: t('Razón (opcional)', 'Reason (optional)', 'وجہ (اختیاری)'),
      reassignHistory: t('Historial de reasignación', 'Reassignment history', 'دوبارہ تفویض کی تاریخ'),
      tasksReassigned: t('tareas reasignadas', 'tasks reassigned', 'دوبارہ تفویض شدہ کام'),

      // ── Milestones (Phase 2) ──
      milestones: t('Hitos', 'Milestones', 'سنگ میل'),
      addMilestone: t('Agregar hito', 'Add milestone', 'سنگ میل شامل کریں'),
      targetDate: t('Fecha objetivo', 'Target date', 'مقصد کی تاریخ'),
      milestoneCompleted: t('Hito completado', 'Milestone completed', 'سنگ میل مکمل'),
      noMilestones: t('Sin hitos', 'No milestones', 'کوئی سنگ میل نہیں'),

      // ── Roll-ups (Phase 2) ──
      rollups: t('Resumen', 'Overview', 'جائزہ'),
      completionRate: t('Tasa de completado', 'Completion rate', 'تکمیل کی شرح'),
      openTasks: t('Tareas abiertas', 'Open tasks', 'کھلے کام'),
      avgCycleTime: t('Tiempo de ciclo promedio', 'Avg cycle time', 'اوسط چکر وقت'),
      projectHealth: t('Salud del proyecto', 'Project health', 'پروجیکٹ کی صحت'),

      // ── Sprints (Phase 3) ──
      sprints: t('Sprints', 'Sprints', 'سپرنٹس'),
      createSprint: t('Crear sprint', 'Create sprint', 'سپرنٹ بنائیں'),
      sprintName: t('Nombre del sprint', 'Sprint name', 'سپرنٹ کا نام'),
      sprintGoal: t('Objetivo del sprint', 'Sprint goal', 'سپرنٹ کا مقصد'),
      startDate: t('Fecha de inicio', 'Start date', 'شروع کی تاریخ'),
      endDate: t('Fecha de fin', 'End date', 'اختتام کی تاریخ'),
      activeSprint: t('Sprint activo', 'Active sprint', 'فعال سپرنٹ'),
      plannedSprint: t('Planificado', 'Planned', 'منصوبہ بند'),
      completedSprint: t('Completado', 'Completed', 'مکمل'),
      startSprint: t('Iniciar sprint', 'Start sprint', 'سپرنٹ شروع کریں'),
      completeSprint: t('Completar sprint', 'Complete sprint', 'سپرنٹ مکمل کریں'),
      noSprints: t('Sin sprints', 'No sprints', 'کوئی سپرنٹ نہیں'),

      // ── Reports (Phase 3) ──
      reports: t('Reportes', 'Reports', 'رپورٹس'),
      burndownChart: t('Gráfico Burndown', 'Burndown Chart', 'برن ڈاؤن چارٹ'),
      velocityChart: t('Gráfico de Velocidad', 'Velocity Chart', 'رفتار چارٹ'),
      cumulativeFlow: t('Flujo Acumulado', 'Cumulative Flow', 'مجموعی بہاؤ'),
      cycleTime: t('Tiempo de Ciclo', 'Cycle Time', 'چکر وقت'),
      sprintReport: t('Reporte de Sprint', 'Sprint Report', 'سپرنٹ رپورٹ'),

      // ── Goals & OKRs (Phase 3) ──
      goals: t('Objetivos y OKRs', 'Goals & OKRs', 'اہداف اور OKRs'),
      createGoal: t('Crear objetivo', 'Create goal', 'ہدف بنائیں'),
      objective: t('Objetivo', 'Objective', 'مقصد'),
      keyResult: t('Resultado Clave', 'Key Result', 'کلیدی نتیجہ'),
      goal: t('Meta', 'Goal', 'ہدف'),
      progress: t('Progreso', 'Progress', 'پیشرفت'),
      targetValue: t('Valor objetivo', 'Target value', 'ہدف قدر'),
      currentValue: t('Valor actual', 'Current value', 'موجودہ قدر'),
      unit: t('Unidad', 'Unit', 'اکائی'),
      period: t('Período', 'Period', 'مدت'),
      linkProject: t('Vincular proyecto', 'Link project', 'پروجیکٹ جوڑیں'),
      linkTask: t('Vincular tarea', 'Link task', 'کام جوڑیں'),
      noGoals: t('Sin objetivos aún', 'No goals yet', 'ابھی کوئی اہداف نہیں'),
      assignToProject: t('Asignar a proyecto', 'Assign to project', 'پروجیکٹ کو تفویض کریں'),
      noProjectAssigned: t('Sin proyecto', 'No project', 'کوئی پروجیکٹ نہیں'),
      generalGoals: t('General', 'General', 'عمومی'),
      filterByProject: t('Filtrar por proyecto', 'Filter by project', 'پروجیکٹ سے فلٹر کریں'),
      goalActive: t('Activo', 'Active', 'فعال'),
      goalCompleted: t('Completado', 'Completed', 'مکمل'),
      goalCancelled: t('Cancelado', 'Cancelled', 'منسوخ'),

      // ── Roadmap (Phase 3) ──
      roadmap: t('Roadmap', 'Roadmap', 'روڈ میپ'),
      timeline: t('Línea de tiempo', 'Timeline', 'ٹائم لائن'),
      quarter: t('Trimestre', 'Quarter', 'سہ ماہی'),
      week: t('Semana', 'Week', 'ہفتہ'),
      month: t('Mes', 'Month', 'مہینہ'),
      projectsAndTasks: t('Proyectos y Tareas', 'Projects & Tasks', 'پروجیکٹس اور کام'),
      dependencies: t('Dependencias', 'Dependencies', 'انحصار'),
      expandAll: t('Expandir todo', 'Expand all', 'سب پھیلائیں'),
      collapseAll: t('Colapsar todo', 'Collapse all', 'سب سمیٹیں'),
      noTasksWithDates: t('Sin tareas con fechas', 'No tasks with dates', 'تاریخ والے کام نہیں'),
      projectDependencies: t('Dependencias de proyecto', 'Project dependencies', 'پروجیکٹ انحصار'),
      addDependency: t('Agregar dependencia', 'Add dependency', 'انحصار شامل کریں'),
      dependsOn: t('Depende de', 'Depends on', 'انحصار کرتا ہے'),
      noDependencies: t('Sin dependencias', 'No dependencies', 'کوئی انحصار نہیں'),

      // ── Agenda ──
      agenda: t('Agenda', 'Agenda', 'ایجنڈا'),
      teamAgenda: t('Agenda del Equipo', 'Team Agenda', 'ٹیم ایجنڈا'),
      blockTime: t('Bloquear tiempo', 'Block time', 'وقت مسدود کریں'),
      reserveTime: t('Reservar tiempo', 'Reserve time', 'وقت محفوظ کریں'),
      reservedDates: t('Fechas reservadas', 'Reserved dates', 'محفوظ تاریخیں'),
      vacation: t('Vacaciones', 'Vacation', 'چھٹی'),
      personal: t('Personal', 'Personal', 'ذاتی'),
      busy: t('Ocupado', 'Busy', 'مصروف'),
      noEventsDay: t('Sin eventos', 'No events', 'کوئی ایونٹ نہیں'),
      conflict: t('Conflicto', 'Conflict', 'تنازعہ'),
      conflictDetected: t('Conflicto detectado: participante tiene tiempo reservado', 'Conflict detected: attendee has reserved time', 'تنازعہ پایا گیا: شریک کا وقت محفوظ ہے'),
      tasksLabel: t('Tareas', 'Tasks', 'کام'),
      meetingsLabel: t('Reuniones', 'Meetings', 'میٹنگز'),
      reservedLabel: t('Reservado', 'Reserved', 'محفوظ'),
      prevWeek: t('Semana anterior', 'Previous week', 'پچھلا ہفتہ'),
      nextWeek: t('Semana siguiente', 'Next week', 'اگلا ہفتہ'),
      weekOf: t('Semana del', 'Week of', 'ہفتہ'),
      errorCreatingReservedDate: t('Error al crear fecha reservada', 'Error creating reserved date', 'محفوظ تاریخ بنانے میں خرابی'),
      reservedDateCreated: t('Tiempo bloqueado exitosamente', 'Time blocked successfully', 'وقت کامیابی سے مسدود ہو گیا'),
      deleteReservedDate: t('Eliminar fecha reservada', 'Delete reserved date', 'محفوظ تاریخ حذف کریں'),

      // ── Workflow Builder ──
      workflows: t('Workflows', 'Workflows', 'ورک فلوز'),
      workflowBuilder: t('Workflow Builder', 'Workflow Builder', 'ورک فلو بلڈر'),
      workflowBuilderDesc: t('Crea flujos automatizados con agentes AI, publicaciones en redes y generación de video', 'Build automated flows with AI agents, social media posts, and video generation', 'AI ایجنٹس، سوشل میڈیا پوسٹس، اور ویڈیو جنریشن کے ساتھ خودکار فلوز بنائیں'),
      newWorkflow: t('Nuevo workflow', 'New workflow', 'نیا ورک فلو'),
      workflowName: t('Nombre del workflow', 'Workflow name', 'ورک فلو کا نام'),
      workflowType: t('Tipo', 'Type', 'قسم'),
      aiAgentWorkflow: t('Agente AI', 'AI Agent', 'AI ایجنٹ'),
      socialMediaWorkflow: t('Redes Sociales', 'Social Media', 'سوشل میڈیا'),
      videoCreationWorkflow: t('Creación de Video', 'Video Creation', 'ویڈیو تخلیق'),
      aiAgentWorkflowDesc: t('Crea agentes autónomos que ejecutan tareas complejas', 'Create autonomous agents that execute complex tasks', 'پیچیدہ کام انجام دینے والے خودمختار ایجنٹس بنائیں'),
      socialMediaWorkflowDesc: t('Programa y publica contenido en múltiples redes', 'Schedule and publish content across multiple networks', 'متعدد نیٹ ورکس پر مواد شیڈول اور شائع کریں'),
      videoCreationWorkflowDesc: t('Genera videos con Runway AI por sesión', 'Generate videos with Runway AI per session', 'Runway AI کے ساتھ فی سیشن ویڈیوز بنائیں'),
      workflowDraft: t('Borrador', 'Draft', 'مسودہ'),
      workflowActive: t('Activo', 'Active', 'فعال'),
      workflowPaused: t('Pausado', 'Paused', 'روکا ہوا'),
      workflowCompleted: t('Completado', 'Completed', 'مکمل'),
      workflowFailed: t('Fallido', 'Failed', 'ناکام'),
      addNode: t('Agregar nodo', 'Add node', 'نوڈ شامل کریں'),
      deleteNode: t('Eliminar nodo', 'Delete node', 'نوڈ حذف کریں'),
      triggerNode: t('Disparador', 'Trigger', 'ٹریگر'),
      aiPromptNode: t('Prompt AI', 'AI Prompt', 'AI پرامپٹ'),
      aiAgentNode: t('Agente AI', 'AI Agent', 'AI ایجنٹ'),
      socialPostNode: t('Post Social', 'Social Post', 'سوشل پوسٹ'),
      videoGenerateNode: t('Generar Video', 'Generate Video', 'ویڈیو بنائیں'),
      imageGenerateNode: t('Generar Imagen', 'Generate Image', 'تصویر بنائیں'),
      conditionNode: t('Condición', 'Condition', 'شرط'),
      delayNode: t('Espera', 'Delay', 'تاخیر'),
      transformNode: t('Transformar', 'Transform', 'تبدیل'),
      outputNode: t('Salida', 'Output', 'آؤٹ پٹ'),
      runWorkflow: t('Ejecutar', 'Run', 'چلائیں'),
      runHistory: t('Historial de ejecuciones', 'Run history', 'عمل درآمد کی تاریخ'),
      noWorkflows: t('No hay workflows creados', 'No workflows created', 'کوئی ورک فلو نہیں بنایا گیا'),
      createFirst: t('Crea tu primer workflow automatizado', 'Create your first automated workflow', 'اپنا پہلا خودکار ورک فلو بنائیں'),
      useTemplate: t('Usar plantilla', 'Use template', 'ٹیمپلیٹ استعمال کریں'),
      fromScratch: t('Desde cero', 'From scratch', 'شروع سے'),
      templateContentCalendar: t('Calendario de contenido', 'Content calendar', 'مواد کیلنڈر'),
      templateVideoSeries: t('Serie de videos', 'Video series', 'ویڈیو سیریز'),
      templateAgentPipeline: t('Pipeline de agentes', 'Agent pipeline', 'ایجنٹ پائپ لائن'),
      nodeConfig: t('Configuración del nodo', 'Node configuration', 'نوڈ کی ترتیب'),
      prompt: t('Prompt', 'Prompt', 'پرامپٹ'),
      model: t('Modelo', 'Model', 'ماڈل'),
      platform: t('Plataforma', 'Platform', 'پلیٹ فارم'),
      instagram: t('Instagram', 'Instagram', 'انسٹاگرام'),
      twitter: t('Twitter / X', 'Twitter / X', 'ٹوئٹر / ایکس'),
      linkedin: t('LinkedIn', 'LinkedIn', 'لنکڈ ان'),
      tiktok: t('TikTok', 'TikTok', 'ٹک ٹاک'),
      runwayModel: t('Modelo Runway', 'Runway Model', 'رن وے ماڈل'),
      videoDuration: t('Duración del video', 'Video duration', 'ویڈیو کی مدت'),
      videoStyle: t('Estilo del video', 'Video style', 'ویڈیو کا انداز'),
      seconds5: t('5 segundos', '5 seconds', '5 سیکنڈ'),
      seconds10: t('10 segundos', '10 seconds', '10 سیکنڈ'),
      caption: t('Texto / Caption', 'Caption / Text', 'کیپشن / ٹیکسٹ'),
      hashtags: t('Hashtags', 'Hashtags', 'ہیش ٹیگز'),
      scheduleAt: t('Programar para', 'Schedule at', 'کے لیے شیڈول'),
      lastRun: t('Última ejecución', 'Last run', 'آخری عمل'),
      totalRuns: t('Ejecuciones', 'Runs', 'عمل'),
      workflowSaved: t('Workflow guardado', 'Workflow saved', 'ورک فلو محفوظ ہو گیا'),
      workflowDeleted: t('Workflow eliminado', 'Workflow deleted', 'ورک فلو حذف ہو گیا'),
      workflowExecutedOk: t('Workflow ejecutado exitosamente', 'Workflow executed successfully', 'ورک فلو کامیابی سے چل گیا'),
      workflowExecutedError: t('Error en la ejecución', 'Execution error', 'عمل میں خرابی'),
      executionFailed: t('Fallo en la ejecución', 'Execution failed', 'عمل ناکام'),
      triggerNodeDesc: t('Iniciar el workflow', 'Start the workflow', 'ورک فلو شروع کریں'),
      aiPromptNodeDesc: t('Enviar un prompt a un modelo AI', 'Send a prompt to an AI model', 'AI ماڈل کو پرامپٹ بھیجیں'),
      aiAgentNodeDesc: t('Ejecutar un agente AI autónomo', 'Run an autonomous AI agent', 'خودمختار AI ایجنٹ چلائیں'),
      socialPostNodeDesc: t('Publicar en redes sociales', 'Publish to social media', 'سوشل میڈیا پر شائع کریں'),
      videoGenerateNodeDesc: t('Generar video con Runway AI', 'Generate video with Runway AI', 'Runway AI سے ویڈیو بنائیں'),
      imageGenerateNodeDesc: t('Generar una imagen con AI', 'Generate an image with AI', 'AI سے تصویر بنائیں'),
      conditionNodeDesc: t('Ramificar según condición', 'Branch based on condition', 'شرط کی بنیاد پر شاخ'),
      delayNodeDesc: t('Esperar antes de continuar', 'Wait before continuing', 'جاری رکھنے سے پہلے انتظار'),
      transformNodeDesc: t('Transformar datos entre nodos', 'Transform data between nodes', 'نوڈز کے درمیان ڈیٹا تبدیل'),
      outputNodeDesc: t('Salida final del workflow', 'Final output of the workflow', 'ورک فلو کی حتمی آؤٹ پٹ'),
      placeholderPrompt: t('Escribe tu prompt...', 'Write your prompt...', 'اپنا پرامپٹ لکھیں...'),
      placeholderAgentTask: t('Define la tarea del agente...', 'Define the agent task...', 'ایجنٹ کا کام بیان کریں...'),
      placeholderPostContent: t('Escribe el contenido del post...', 'Write your post content...', 'پوسٹ کا مواد لکھیں...'),
      placeholderVideoPrompt: t('Un plano cinematográfico de una ciudad al atardecer...', 'A cinematic drone shot of a city at sunset...', 'غروب آفتاب پر شہر کا سنیما شاٹ...'),
      placeholderImagePrompt: t('Una foto profesional de producto...', 'A professional product photo...', 'ایک پیشہ ورانہ پروڈکٹ فوٹو...'),
      templateContentDesc: t('AI genera contenido -> post en redes sociales', 'AI generates content -> social media post', 'AI مواد بناتا ہے -> سوشل میڈیا پوسٹ'),
      templateVideoDesc: t('Script AI -> Video Runway -> Post', 'AI Script -> Runway Video -> Post', 'AI اسکرپٹ -> Runway ویڈیو -> پوسٹ'),
      templateAgentDesc: t('Agente AI multi-paso con transformación', 'Multi-step AI agent with transformation', 'تبدیلی کے ساتھ ملٹی اسٹیپ AI ایجنٹ'),
      apiKeys: t('Claves API', 'API Keys', 'API کیز'),
      apiKeysDesc: t('Configura las claves de los servicios externos', 'Configure external service API keys', 'بیرونی خدمات کی API کیز ترتیب دیں'),
      openrouterKey: t('Clave OpenRouter', 'OpenRouter Key', 'OpenRouter کی'),
      runwayKey: t('Clave Runway', 'Runway Key', 'Runway کی'),
      instagramToken: t('Token Instagram', 'Instagram Token', 'انسٹاگرام ٹوکن'),
      twitterToken: t('Token Twitter / X', 'Twitter / X Token', 'ٹوئٹر / X ٹوکن'),
      linkedinToken: t('Token LinkedIn', 'LinkedIn Token', 'لنکڈ ان ٹوکن'),
      tiktokToken: t('Token TikTok', 'TikTok Token', 'ٹک ٹاک ٹوکن'),
      apiKeysSaved: t('Claves guardadas', 'Keys saved', 'کیز محفوظ ہو گئیں'),
      apiKeysPlaceholder: t('Pega tu clave aquí...', 'Paste your key here...', 'اپنی کی یہاں پیسٹ کریں...'),
      configureKeys: t('Configurar claves', 'Configure keys', 'کیز ترتیب دیں'),
      sendEmailNode: t('Enviar Email', 'Send Email', 'ای میل بھیجیں'),
      sendEmailNodeDesc: t('Enviar un correo electrónico', 'Send an email message', 'ایک ای میل پیغام بھیجیں'),
      webhookNode: t('Webhook', 'Webhook', 'ویب ہک'),
      webhookNodeDesc: t('Llamar a un endpoint HTTP externo', 'Call an external HTTP endpoint', 'بیرونی HTTP اینڈ پوائنٹ کال کریں'),
      httpRequestNode: t('HTTP Request', 'HTTP Request', 'HTTP ریکوئسٹ'),
      httpRequestNodeDesc: t('Hacer una petición HTTP personalizada', 'Make a custom HTTP request', 'اپنی مرضی کی HTTP ریکوئسٹ بنائیں'),
      emailTo: t('Destinatario', 'Recipient', 'وصول کنندہ'),
      emailSubject: t('Asunto', 'Subject', 'موضوع'),
      emailBody: t('Cuerpo del mensaje', 'Message body', 'پیغام کا متن'),
      webhookUrl: t('URL del webhook', 'Webhook URL', 'ویب ہک URL'),
      httpMethod: t('Método HTTP', 'HTTP Method', 'HTTP طریقہ'),
      httpUrl: t('URL', 'URL', 'URL'),
      httpHeaders: t('Headers (JSON)', 'Headers (JSON)', 'ہیڈرز (JSON)'),
      httpBody: t('Body (JSON)', 'Body (JSON)', 'باڈی (JSON)'),
      placeholderEmail: t('correo@ejemplo.com', 'email@example.com', 'ای میل@مثال.com'),
      placeholderSubject: t('Asunto del correo...', 'Email subject...', 'ای میل کا موضوع...'),
      placeholderEmailBody: t('Contenido del correo...', 'Email content...', 'ای میل کا مواد...'),

      // ── Workflow Chat Assistant ──
      workflowAssistant: t('Asistente AI', 'AI Assistant', 'AI اسسٹنٹ'),
      workflowAssistantDesc: t('Describe lo que quieres y el AI creará los nodos', 'Describe what you want and AI will create the nodes', 'بیان کریں کہ آپ کیا چاہتے ہیں اور AI نوڈز بنائے گا'),
      workflowChatPlaceholder: t('Ej: "Crea un workflow que genere contenido y lo publique en Instagram y Twitter"', 'E.g.: "Create a workflow that generates content and posts to Instagram and Twitter"', 'مثال: "ایک ورک فلو بنائیں جو مواد تیار کرے اور انسٹاگرام اور ٹوئٹر پر پوسٹ کرے"'),
      workflowChatSend: t('Enviar', 'Send', 'بھیجیں'),
      workflowChatThinking: t('Pensando...', 'Thinking...', 'سوچ رہا ہے...'),
      workflowNodesApplied: t('Nodos aplicados al workflow', 'Nodes applied to workflow', 'نوڈز ورک فلو پر لاگو ہو گئے'),
      sessionActive: t('Sesion con memoria activa', 'Session with active memory', 'فعال میموری کے ساتھ سیشن'),
      newSession: t('Nueva conversacion', 'New conversation', 'نئی گفتگو'),
      chatHistory: t('Historial de chats', 'Chat history', 'چیٹ ہسٹری'),
      noSessions: t('No hay conversaciones previas', 'No previous conversations', 'کوئی پچھلی گفتگو نہیں'),
      workflowChatWelcome: t('Hola! Puedo ayudarte a crear tu workflow. Describe lo que necesitas y creare los nodos automaticamente.', 'Hi! I can help you build your workflow. Describe what you need and I will create the nodes automatically.', 'ہائے! میں آپ کا ورک فلو بنانے میں مدد کر سکتا ہوں۔ بیان کریں کہ آپ کو کیا چاہیے اور میں خودکار طور پر نوڈز بناؤں گا۔'),
      workflowSuggestion1: t('Genera contenido para redes sociales', 'Generate social media content', 'سوشل میڈیا کا مواد بنائیں'),
      workflowSuggestion2: t('Crea un pipeline de video con Runway', 'Create a video pipeline with Runway', 'Runway کے ساتھ ویڈیو پائپ لائن بنائیں'),
      workflowSuggestion3: t('Automatiza reportes con email', 'Automate reports with email', 'ای میل کے ساتھ رپورٹس خودکار کریں'),
      nodeCategories: t('Categorias', 'Categories', 'زمرے'),
      catAI: t('Inteligencia Artificial', 'Artificial Intelligence', 'مصنوعی ذہانت'),
      catSocial: t('Redes Sociales', 'Social Media', 'سوشل میڈیا'),
      catMedia: t('Media', 'Media', 'میڈیا'),
      catIntegrations: t('Integraciones', 'Integrations', 'انٹیگریشنز'),
      catLogic: t('Logica', 'Logic', 'منطق'),
      n8nConnected: t('n8n conectado', 'n8n connected', 'n8n منسلک'),
      n8nDisconnected: t('n8n no conectado', 'n8n not connected', 'n8n منسلک نہیں'),
      n8nNotConfigured: t('n8n no configurado', 'n8n not configured', 'n8n ترتیب نہیں دیا گیا'),
      n8nUrl: t('URL de n8n', 'n8n URL', 'n8n URL'),
      n8nApiKey: t('API Key de n8n', 'n8n API Key', 'n8n API کی'),
      n8nDesc: t('Conecta n8n para ejecutar workflows avanzados con 400+ integraciones', 'Connect n8n to run advanced workflows with 400+ integrations', 'n8n کو 400+ انٹیگریشنز کے ساتھ ایڈوانسڈ ورک فلوز چلانے کے لیے منسلک کریں'),
      n8nWorkflows: t('workflows en n8n', 'workflows in n8n', 'n8n میں ورک فلوز'),
      engineBuiltin: t('Motor integrado', 'Built-in engine', 'بلٹ ان انجن'),
      engineN8n: t('Motor n8n', 'n8n engine', 'n8n انجن'),
      checkConnection: t('Verificar conexion', 'Check connection', 'کنکشن چیک کریں'),

      // ── Motivational ──
      motivationalToast: t('Tip del día', 'Tip of the day', 'آج کی نصیحت'),

      // ── Admin Panel ──
      adminUsers: t('Usuarios', 'Users', 'صارفین'),
      adminPanel: t('Panel Admin', 'Admin Panel', 'ایڈمن پینل'),
      adminPanelDesc: t('Vista global de todos los usuarios de la plataforma', 'Global view of all platform users', 'تمام پلیٹ فارم صارفین کا عالمی نظارہ'),
      totalUsers: t('Usuarios Totales', 'Total Users', 'کل صارفین'),
      activeToday: t('Activos hoy', 'Active today', 'آج فعال'),
      withWorkspace: t('Con workspace', 'With workspace', 'ورک سپیس کے ساتھ'),
      noWorkspace: t('Sin workspace', 'No workspace', 'ورک سپیس نہیں'),
      searchUsers: t('Buscar por email...', 'Search by email...', 'ای میل سے تلاش کریں...'),
      lastLogin: t('Último login', 'Last login', 'آخری لاگ ان'),
      never: t('Nunca', 'Never', 'کبھی نہیں'),
      tasksAssigned: t('Tareas asignadas', 'Tasks assigned', 'تفویض شدہ کام'),
      completed: t('Completadas', 'Completed', 'مکمل'),
      inProgress: t('En progreso', 'In progress', 'جاری'),
      workspacesLabel: t('Workspaces', 'Workspaces', 'ورک سپیسز'),
      membersLabel: t('Miembros', 'Members', 'ممبران'),
      projectsLabel: t('Proyectos', 'Projects', 'پروجیکٹس'),
      registeredOn: t('Registrado el', 'Registered on', 'رجسٹرڈ'),
      noUsersFound: t('No se encontraron usuarios', 'No users found', 'کوئی صارف نہیں ملا'),
      loadingUsers: t('Cargando usuarios...', 'Loading users...', 'صارفین لوڈ ہو رہے ہیں...'),
      addToWorkspace: t('Agregar a workspace', 'Add to workspace', 'ورک سپیس میں شامل کریں'),
      selectWorkspace: t('Seleccionar workspace', 'Select workspace', 'ورک سپیس منتخب کریں'),
      selectRole: t('Seleccionar rol', 'Select role', 'کردار منتخب کریں'),
      addedToWorkspace: t('agregado al workspace', 'added to workspace', 'ورک سپیس میں شامل'),
      manageProjectAccess: t('Gestionar acceso a proyectos', 'Manage project access', 'پروجیکٹ تک رسائی کا انتظام'),
      userAlreadyInWorkspace: t('El usuario ya es miembro de este workspace', 'User is already a member of this workspace', 'صارف پہلے سے اس ورک سپیس کا ممبر ہے'),
      adminAutoAccessShort: t('Admin+ tiene acceso a todos los proyectos', 'Admin+ has access to all projects', 'ایڈمن+ کو تمام پروجیکٹس تک رسائی ہے'),
      selectProjects: t('Seleccionar proyectos', 'Select projects', 'پروجیکٹس منتخب کریں'),
      projectsUpdated: t('Proyectos actualizados', 'Projects updated', 'پروجیکٹس اپ ڈیٹ ہو گئے'),
      noProjectsInWorkspace: t('Este workspace no tiene proyectos', 'This workspace has no projects', 'اس ورک سپیس میں کوئی پروجیکٹ نہیں'),
      actions: t('Acciones', 'Actions', 'اعمال'),
    }
  })

  return {
    language: currentLanguage,
    setLanguage,
    toggleLanguage,
    localizedTitle,
    localizedDescription,
    labels,
  }
}
